### PR TITLE
new: reader view: footer has manage icons

### LINKED ISSUE #7115: [Feature] Put the read/unread and favourite buttons at the bottom of articles in reader view
**Is your feature request related to a problem? Please describe.**
When I read articles in reader view it's annoying to scroll back up to the top of the article to mark the article as read and/or unfavourite it.

**Describe the solution you’d like**
Putting both buttons at the bottom would solve this problem.

**Additional context**
grafik

### PR DESCRIPTION
**Pull request by math-GH**
Closes #7115

Reader view

After:
added: read/unread, favorite, date, link external website
not added (will be another PR later): my labels, article tags, share menu

grafik

How to test the feature manually:

1. go to reader view
2. see the bottom of article
3. the buttons depends on the selected article icons in display config

Pull request checklist:

- [ ] clear commit messages
- [ ] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by Alkarex** [comment]
I think we should reuse the layout of the normal view, potentially with minor tweaks. The reader view is lacking many features, which have been added to the normal view, such as user labels, authors, feed, etc.

**Comment by math-GH** [comment]
It is not that easy.... :/ Because of the `horizontal lists` in normal view that are not implementable in reader view as it is now. I would say that the reader view should be more than just the normal view fully expanded.

**Comment by Inverle** [comment]
> not added (will be another PR later): my labels, article tags, share menu

Is there an issue for tracking this?

**Comment by math-GH** [comment]
> > not added (will be another PR later): my labels, article tags, share menu
> 
> Is there an issue for tracking this?

No, I cannot remember to have it. But it is deeeeep in my mind :D

**Pull request merged**
