### PR TITLE
 Fix thumbnail PHP type hint

### LINKED ISSUE #4215: Single Items showing up even when more are avaiable in Normal View
I have been on the development track from 1.17 -> 1.20 and all have been great until the latest update in 1.20.0-dev.  Thank you devs for all you do to keep the application innovative and adding such great features.  

The issue I have recently run into is my 'Main Stream'  or any of the sub groups only shows a single item only even when there are many other unread items using the Normal View pane.  Wondering if I'm missing something obvious here.  I tried the top buttons to select unread/read, unstarred, stared, etc. to no eval.  I mostly access the application using a third-part reader so it is not a big issue at this time, but was not sure if this effects others.  

Setup:
FreshRss running on RasberryPi
Browser accessing is Chrome (98.0.4758)

Attached images to show what I'm saying above.
Screen Shot 2022-02-09 at 10 02 15 AM
Screen Shot 2022-02-09 at 9 48 55 AM

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/4215

### CODE REVIEW

**Comment by Frenzie** [comment]
What's a feed that has some btw?

**Comment by Alkarex** [comment]
> What's a feed that has some btw?

@Frenzie We take the first enclosure as the "thumbnail".

**Comment by Frenzie** [comment]
Right, what's a sample feed with enclosures? I may have 100+ feeds but none of them use enclosures.

**Comment by Alkarex** [comment]
See for instance http://feeds.feedburner.com/hackaday/LgoM

```xml
<media:thumbnail url="[https://hackaday.com/wp-content/uploads/2022/02/twist-feature.png]()" />
<media:content url="[https://hackaday.com/wp-content/uploads/2022/02/twist-feature.png]()" medium="[image]()">
	<media:title type="[html]()">twist-feature</media:title>
</media:content>
```

**Pull request merged**
