### PR TITLE
improved: article footer for small displays

### PR DESCRIPTION
**Pull request by math-GH**
Before:
on small screens the article footer links for `my labels`, `article tags`, `share` could have a line break

grafik

After:
Do not show the text of the links, if the main stream is smaller than 600px.
grafik

Changes proposed in this pull request:

- CSS. Use of `@container` queries.

How to test the feature manually:

1. normal view
2. change the size of the window
3. see the article footer

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
I have not checked: what is the behaviour on Web browser not supporting `@container` ?

**Comment by Frenzie** [comment]
I think this isn't quite the right solution. It's almost entirely identical to a regular media query, still subject to what the user has or hasn't enabled, while the power of container queries is that you could stick it on the individual elements.

That's not an objection to this form, but I'd just stick it under `@media (max-width: 840px) {` in that case.

**Comment by math-GH** [comment]
> I have not checked: what is the behaviour on Web browser not supporting `@container` ?

It should happen nothing, because the text will not be hidden in that case. It would look like "before".

**Comment by math-GH** [comment]
> I think this isn't quite the right solution. It's almost entirely identical to a regular media query, still subject to what the user has or hasn't enabled, while the power of container queries is that you could stick it on the individual elements.
> 
> That's not an objection to this form, but I'd just stick it under `@media (max-width: 840px) {` in that case.

Okay, let me explain a bit what happend while I tried to find a solution. I invested a couple of hours to investigate what works and what does not work and what fit best:

Idea 1: use the Container query directly at the individual element. It is not easy to implement, because it does not work in inline elements. But I managed it. But: The dropdown menu does not work anymore because the container cuts everything that would overlay outside the container. The menu will be cut.

Idea 2: use the default media query as suggested but it is not the best solution. Between 840px (media query) and 600px (container break point) is enough space to display the text. 

That is why I chose this solution by purpose that you can see in this PR

**Comment by Frenzie** [comment]
> I have not checked: what is the behaviour on Web browser not supporting `@container` ?

Forgot to say, but it's just as if it wasn't there.

**Comment by Alkarex** [comment]
Let's go for that but feel free to propose another approach @Frenzie

**Pull request merged**
