### PR TITLE
Improved: Theme nord more improvement

### PR DESCRIPTION
**Pull request by math-GH**
Ref #5689

Changes proposed in this pull request:

some little improvements for the `Nord` theme that makes it a little bit better

### CODE REVIEW

**Comment by math-GH** [comment]
New article banner

Before:
grafik


After:
grafik

**Comment by math-GH** [comment]
Side menu: Closing button, width, blurred dark area

Before:
grafik

After:
grafik

**Comment by math-GH** [comment]
Dropdown menu

Before:
grafik


After:
grafik

**Comment by daffydock** [comment]
Just as FYI, I tried using Nord again. The newest version and remembered that I had some custom CSS for a theme. Removed that, refreshed, and the theme looks just as pictured. So likely, just my bad. Again, great work in improving a great theme. Cheers.

**Pull request merged**
