### PR TITLE
Update README.md for ReadKit

### PR DESCRIPTION
**Pull request by gingerbeardman**
I use ReadKit (free version) on iOS and macOS. 

Pro purchase is required to manage feeds, which I don't agree with given that we're using FreshRSS. Managing local feeds I can understand that could be value add.

Changes proposed in this pull request:

- correct ReadKit info

Pull request checklist:

- [X] clear commit messages
- [X] documentation updated

### CODE REVIEW

**Comment by gingerbeardman** [comment]
> I use ReadKit (free version) on iOS and macOS.
> 
> Pro purchase is required to manage feeds, which I don't agree with given that we're using FreshRSS. Managing local feeds I can understand that could be value add.
> 
> Changes proposed in this pull request:
> 
> * correct ReadKit info
> 
> Pull request checklist:
> 
> * [x]  clear commit messages
> * [x]  documentation updated

**Comment by aledeg** [comment]
@gingerbeardman I would add a footnote on the manage feed to mentioned that you need to pay for that in-app feature.

**Comment by Alkarex** [comment]
I have finally found an iOS device and the time to test and update the remaining details.

**Comment by gingerbeardman** [comment]
Many thanks

**Pull request merged**
