### PR TITLE
Replace screenshot for token configuration   @Alwaysin

### PR DESCRIPTION
**Pull request by Alwaysin**
See https://github.com/FreshRSS/FreshRSS/discussions/5619

### CODE REVIEW

**Comment by Alkarex** [comment]
I can see that we also need to fix the text in the UI. The token is per user, not only for the default user

**Comment by Alwaysin** [comment]
Would replacing "default" by "current" do the trick? Or maybe "of your user" instead of "of the default user".
In french "de l’utilisateur par défaut" to "de l’utilisateur actuel" or "de votre utilisateur", but we'll have the other languages to update.

**Comment by Frenzie** [comment]
Like this?

`Allows access to the RSS output for this user without authentication:`

**Comment by Alkarex** [comment]
Maybe even in plural for outputs:

> Allows access to the RSS outputs for this user without authentication:

**Pull request closed without merging**
