### PR TITLE
Fix Minz link

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/marienfressinaud/MINZ returned 404
Found on https://framagit.org/marienfressinaud/MINZ instead

### CODE REVIEW

**Comment by marien-probesys** [comment]
Sorry, I should have thought of it myself :| Furthermore, I don't think it's useful to still link to this (archived) repository: FreshRSS fork changed significantly, and I will not work on the initial repo anymore.

**Comment by marienfressinaud** [comment]
Sorry, I should have thought of it myself :| Furthermore, I don't think it's useful to still link to this (archived) repository: FreshRSS fork changed significantly, and I will not work on the initial repo anymore.

**Comment by Alkarex** [comment]
It is still a better link than the previous one, isn't it? :-)

**Comment by marienfressinaud** [comment]
Indeed :smile: But I don't mind if you want to remove it :)

**Review by marienfressinaud — APPROVED** [review]

**Pull request merged**
