### PR TITLE
Improved: config user settings in slider

### PR DESCRIPTION
**Pull request by math-GH**
Before:
Manage a user in a "full screen" mode.

grafik

grafik

After:
Manage user in the slider.
Advantage: Similar UX as the other configurations. It does not need a full page reload.

grafik

grafik

How to test the feature manually:

1. go to user management
2. edit a user
3. the slider opens
4. do some user changes

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
Could you please check the status before / after this PR when JavaScript is disabled? (it was probably already something not supported without JavaScript)

**Comment by math-GH** [comment]
> Could you please check the status before / after this PR when JavaScript is disabled? (it was probably already something not supported without JavaScript)

Before PR without Javascript: It opens the page to edit the user config. A noscript warning is given. Did not check for what it is used for. I guess it is connected with the Purge/Remove buttons ("Are you sure?" confirmation prompt)

grafik

**Comment by math-GH** [comment]
How to proceed here @Alkarex ?

**Comment by Alkarex** [comment]
Sorry for the delay. Tested and looks good 👍🏻

**Pull request merged**
