### PR TITLE
fixed: add feed: advanced: white space char as default password

### PR DESCRIPTION
**Pull request by math-GH**
before:
grafik
the default password was a white space char

Changes proposed in this pull request:
- empty string as password

Pull request checklist:
- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by aledeg** [comment]
That was bugging me for a while now, but I never done anything about it. Thank you!

**Review by aledeg — APPROVED** [review]

**Comment by Alkarex** [comment]
This was voluntary due to aggressive autocomplete systems. The risk is to autocomplete this field with a password of the instance, and leak it to the feed being added.
We need to re-check the behaviour with the main browsers, with password/forms autocomplete enabled, after this change

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/880
https://github.com/FreshRSS/FreshRSS/pull/881
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by math-GH** [comment]
it is set autocomplete="new-password" and should prevent the autofill.

more information about autocomplete="off" behavior of the major browsers:
https://caniuse.com/?search=autocomplete

**Comment by math-GH** [comment]
could it be a problem, that it is not a real password input? Right now it is just a text input
grafik

**Comment by Frenzie** [comment]
Well no, if anything making it a password input makes/made it worse because then you can't see what it's auto-filling. But I think the fairly recent autocomplete=new-password should do the trick now.

https://caniuse.com/mdn-html_global_attributes_autocomplete_new-password

**Comment by Frenzie** [comment]
Sorry, didn't notice https://github.com/FreshRSS/FreshRSS/pull/3814#issuecomment-910096347

**Comment by math-GH** [comment]
any todos left for me?

**Review by Frenzie — APPROVED** [review]
NB I haven't done much testing wrt browser behavior.

**Comment by Alkarex** [comment]
What remains to be done is to test with a few different browsers using full build-in password autocompletion, and potentially a couple of third-party password managers (LastPass...).

**Comment by Frenzie** [comment]
@Alkarex How do you mean password managers exactly? I thought all of them were on-demand?

**Comment by Alkarex** [comment]
> @Alkarex How do you mean password managers exactly? I thought all of them were on-demand?

@Frenzie I am not sure as I am not using anything automatic myself, but I believe some have autocomplete features. To start with, the most important is to test with the ones built-in the browsers.

**Comment by Frenzie** [comment]
I use Enpass. If you want to log in somewhere you click on its icon and then it autofills. LastPass works the same afaik.

Which is to say, it might mess up but only because of some problem located near the mouse and keyboard. ;-)

**Comment by math-GH** [comment]
"fun" fact:
in the settings of an existing feed it looks like this:

grafik

1. a whitespace character in the username, but not in the password
2. the password input is a `type=password` (in "add a feed" it is just a `type="text"`)

**Comment by math-GH** [comment]
I checked this "Add a feed" page with Firefox and its password store. 
It does not recognize the form as password form, because there is no type="password" field.

So I will bring 2 fixes

**Comment by math-GH** [comment]
and the `type=password` inputs has now an button "watch the password plain"

**Comment by math-GH** [comment]
@Frenzie and @aledeg : I commited more stuff after your approval

**Comment by Frenzie** [comment]
All fine by me.

**Comment by Alkarex** [comment]
@mathContao Could you please check the merge conflict?

**Comment by math-GH** [comment]
Anything left that I could do to finish this PR?

**Comment by math-GH** [comment]
mhm. No progress here.... 
I would like to finish this PR but need information what is missed/wrong here

**Comment by Alkarex** [comment]
@mathContao What was needed to do is to try with various built-in and third-party password managers:

> What remains to be done is to test with a few different browsers using full build-in password autocompletion, and potentially a couple of third-party password managers (LastPass...).

https://github.com/FreshRSS/FreshRSS/pull/3814#issuecomment-917661802

I have tested with Firefox, Edge, Chrome, but it should have been more comprehensive, so I am merging because it is now theoretically fine with current browsers, but I still think it is a bit risky.

**Comment by Alkarex** [comment]
P.S. I just see now that there is another instance of `value=" "`

https://github.com/FreshRSS/FreshRSS/blob/c5cfb2ac07f039bb7388dca3a4061755c8403fff/app/views/helpers/feed/update.phtml#L136

**Pull request merged**
