### PR TITLE
Translation Finnish

### PR DESCRIPTION
**Pull request by minna-xD**
Hello and happy Hacktoberfest! 🎃 

I have translated the files to Finnish following the excellent documentation. I hope there's still time to get this PR in as my fourth contribution this year. 🥳 

Changes proposed in this pull request:
- Add Finnish localization

### CODE REVIEW

**Comment by minna-xD** [comment]
image
Oh shoot, I thought everything was looking good but it was out-of-date after all. Git kicks my butt every time I mess something up, so I better not touch anything in haste. Please advice. Should I do the "Update with rebase" option?

**Comment by Frenzie** [comment]
It's talking about a few commits from the last couple of days. Can't hurt in this case.

**Review by Frenzie — APPROVED** [review]

**Comment by Frenzie** [comment]
Are the couple of todos flagged by CI on purpose or todo? If not todo they should be ignored. ^_^

**Comment by minna-xD** [comment]
They certainly are new strings and need translation. Didn't see them in the files at my end! I'll fix that.

**Comment by Alkarex** [comment]
Thanks!
Please double-check https://github.com/FreshRSS/FreshRSS/pull/6954/commits/d973cfa65c123c49e8da5bddcb28845d63c1a314
In particular the lines where I have removed the `DIRTY` flag (to be compared against the English or French version)

**Review by Alkarex — APPROVED** [review]

**Comment by minna-xD** [comment]
Checked and looks good (I compared to en version)!

Thank you very much for your patience, prompt help and processing. I'm very intrigued by this project and especially the localization system (I have a background in translation industry). I'll keep my eye on this!

**Comment by Frenzie** [comment]
It's probably fairly standard for simpler PHP projects, besides gettext.

**Comment by Alkarex** [comment]
Please add a line for you in
https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md

**Pull request merged**
