### PR TITLE
Improved: Alternative Dark theme

### PR DESCRIPTION
**Pull request by math-GH**
While I saw this issue with the too dark font color in #4585 I saw a bunch of colors in a lot of different CSS lines without having an overview of the used colors.

So I started to collect all colors in CSS variables.

``` CSS
:root {
	--background-color-dark: #171717;
	--background-color-middle: #1f1f1f;
	--background-color-light: #262626;
	--background-color-hover: #1d242f;
	--background-color-active: #333;
	--background-color-slider-shadow: rgba(0, 0, 0, 0.5);

	--contrast-background-color: #0062b7;
	--contrast-background-color-hover: #0078E0;
	--contrast-background-color-active: #003461;
	--contrast-background-font-color: #eee;
	--contrast-border-color-hover: #0078E0;

	--contrast-attention-background-color: #912621;
	--contrast-attention-background-color-hover: #be342c;
	--contrast-attention-font-color: #eee;

	--font-color-dark: #666;
	--font-color-middle: #999;
	--font-color-light: #ccc;
	--font-color-contrast: #0062b7;
	--font-color-error: #912621;

	--border-color-dark: #333;
	--border-color-middle: #666;
	--border-color-favorite: #ffc300;
	--border-color-unread:  #e74c3c;

	--empty-feed-color: #e67e22;

	--alert-warn-border-color: #615f20;
	--alert-success-border-color: #18521d;
	--alert-error-border-color: #912621;

	--notification-border-color: #eeb;
	--notification-good-border-color: #0044cb;
	--notification-bad-background-color: #fdd;
	--notification-bad-font-color: #912621;
	--notification-bad-border-color: #ecc;
}
```

With this variables it is very easy now to adjust the colors with CustomCSS extension. Do you want a darker or lighter font color? Change it. Do you do not like the blue color? Change it. Do you want another color for mobile view than desktop view? With little CSS it is adjusted.

Plus some little fixes.
Plus some little visible improvement (f.e. the mouse over background color is now a dark blue).

I kept all colors from the origin Alternative Dark theme.

Changes proposed in this pull request:

- CSS

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
Very nice

**Comment by aledeg** [comment]
Nice! Maybe this could be extended to all themes

**Comment by math-GH** [comment]
> Nice! Maybe this could be extended to all themes

It is planned, but it needs some time.

**Comment by math-GH** [comment]
ping @fabianski7, please have a look on this PR. You created this theme and I want to have an okay from you :)

**Comment by aledeg** [comment]
> > Nice! Maybe this could be extended to all themes
> 
> It is planned, but it needs some time.

I wasn't putting pressure on you :) I was just wondering

**Comment by fabianski7** [comment]
This theme was created a long time ago, and since then I haven't had much time to maintain it. I apologize for that.

You don't need my permission to change it, and I can't even test these changes now because I don't have my FreshRSS instance anymore. And you are a great contributor to this and several other projects, so go ahead 🤟

But I would like to see a picture of how it looks now, is that possible?

Thanks!

**Comment by math-GH** [comment]
Before:
grafik

After:
grafik

**Comment by math-GH** [comment]
You see, nothing much visible changed. Only some small details. Most visible: the hover color is now a bit dark blue instead grey. I took the dark blue from the button hover that was already implemented before.

**Comment by fabianski7** [comment]
Great job! It really got better

**Comment by math-GH** [comment]
Let me ping some users of this theme, who took part in the little survey in #4295 and ask for feedback too:

@miicat 
@triatic
@vonguyenkhang
@gu1ll0me
@beerisgood (I saw already your thumbs up :) )
@Poorchop

**Comment by miicat** [comment]
I actually use now the Dark pink theme, which is based on your theme (basically just changing colors)

The alternative dark theme is looking pretty nice now!

**Comment by vonguyenkhang** [comment]
> Let me ping some users of this theme, who took part in the little survey in #4295 and ask for feedback too:

Sorry do I need to install the latest dev version to try this? I'm using version 1.20.0 now.

Side track: in version 1.20.0, the favicon becomes desaturated when hovered on, which is a bit difficult to accept, especially in the extreme cases when the desaturated icon blends with the dark background. But I think I can live with it after some time.
bandicam 2022-09-22 21-41-05-393_1

**Comment by math-GH** [comment]
> Sorry do I need to install the latest dev version to try this? I'm using version 1.20.0 now.

Right now you need to install this PR branch to test it.

> Side track: in version 1.20.0, the favicon becomes desaturated when hovered on, which is a bit difficult to accept, especially in the extreme cases when the desaturated icon blends with the dark background. But I think I can live with it after some time. 

Thanks for this hint. I will check how to improve. It is a general topic, also with black favicons. See f.e. the Github favicon
grafik

**Comment by math-GH** [comment]
@vonguyenkhang could you please check the newest commits of this PR branch? I improved it.

**Comment by vonguyenkhang** [comment]
> @vonguyenkhang could you please check the newest commits of this PR branch? I improved it.

That's fast!
I think this subtle desaturation is better than in ver 1.20.0
~But somehow the row content shifted a bit when hovered on. Is it intended?~ EDIT: see comment below https://github.com/FreshRSS/FreshRSS/pull/4635#issuecomment-1256389582
~https://user-images.githubusercontent.com/15910168/191789522-646ae848-d884-4b15-b8f5-7febc380b000.mp4~

The separator lines between different days are also a bit different. Is it intended?
image

~(note to self:~
~switch to new: ``rm adark.rtl.css ; rm adark.css ; ln -s adark.rtl.css_new adark.rtl.css ; ln -s adark.css_new adark.css``~
~switch back to original: ``rm adark.rtl.css ; rm adark.css ; ln -s adark.rtl.css_original adark.rtl.css ; ln -s adark.css_original adark.css``)~

**Comment by triatic** [comment]
@math-GH nice improvements. I don't think long titles in the message list should expand when hovered over though, this invokes a horizontal scrollbar and hides the "original site" link.

**Comment by beerisgood** [comment]
nice work! can't wait to see it in stable state 🍺

**Comment by math-GH** [comment]
> @math-GH nice improvements. I don't think long titles in the message list should expand when hovered over though, this invokes a horizontal scrollbar and hides the "original site" link.

It is independent from the theme.
An improvement is already in the pipeline. See #4586

**Comment by math-GH** [comment]
@vonguyenkhang I cannot reproduce your shown issues with Firefox and Chrome on Windows. Which browser do you use?

**Comment by Poorchop** [comment]
These seem like good changes. Consolidating the colors into variables will surely make customizing much easier as you mentioned. I also like the dark blue hover color and it certainly seems more fitting for a dark theme. Nice work.

**Comment by vonguyenkhang** [comment]
> @vonguyenkhang I cannot reproduce your shown issues with Firefox and Chrome on Windows. Which browser do you use?

EDIT: see comment below https://github.com/FreshRSS/FreshRSS/pull/4635#issuecomment-1256389582
~I've just tried again using Chrome 105 incognito mode and Edge 105, and I still see the same, even after clearing server cache.
(lighttpd/1.4.64, php 8.1.7)~
~Is there some way that I can send you my server link & login details privately so that you can take a look?~

~UPDATE: I just realize there's no such problem when I use my office PC. Maybe it's something related to Windows scaling? My office PC res. is 1920x1080 scaling 100%, my home PC res. is 3840x2160 scaling 125%.~
~UPDATE: using office PC, when I zoom the page to something other than 100% then I see the same shift-on-hover as my home PC.~

**Comment by math-GH** [comment]
I cannot reproduce it on win10 with 100%, 125% and 150% on Firefox 104 and Chromium 108 :/

**Comment by vonguyenkhang** [comment]
> I cannot reproduce it on win10 with 100%, 125% and 150% on Firefox 104 and Chromium 108 :/

Is there some way that I can send you my server link & login details privately so that you can take a look?

**Comment by math-GH** [comment]
> > I cannot reproduce it on win10 with 100%, 125% and 150% on Firefox 104 and Chromium 108 :/
> 
> Is there some way that I can send you my server link & login details privately so that you can take a look?

Could you please join https://framateam.org/freshrss/channels/town-square ?

Click on "GitLab" link
grafik

Then you can find the option to use GitHub login.

**Comment by vonguyenkhang** [comment]
> > > I cannot reproduce it on win10 with 100%, 125% and 150% on Firefox 104 and Chromium 108 :/
> > 
> > 
> > Is there some way that I can send you my server link & login details privately so that you can take a look?
> 
> Could you please join https://framateam.org/freshrss/channels/town-square ?
>
> Then you can find the option to use GitHub login.

I tried logging in using GitHub account but I encountered this 

> Erreur
>GitLab's Terms of Service have updated. Please go to gitlab.com to accept them and then try logging into Mattermost again.
>[Retour à Framateam](https://framateam.org/)

How should I proceed? Sorry I'm very new to this.

**Comment by math-GH** [comment]
ok. You could create also a full Framateam account or let's use the good old email. I created a trash email [ deleted ] to keep my privacy here.

**Comment by vonguyenkhang** [comment]
as @math-GH pointed out, I didn't properly install this PR branch and that led to the shift-on-hover issue. 
After properly switching to f6868338634cb596267de56f782377292682d7be, there's no more shift-on-hover issue. (probably because the base-theme was also changed compared with 1.20.0 https://github.com/FreshRSS/FreshRSS/compare/812e6544...f686833)
Sorry for the false alarm and thanks for helping.

**Comment by math-GH** [comment]
Short summary: thanks for your positive feedbacks. All mentioned bugs are fixed.

More feedback is welcome.

**Pull request merged**
