### PR TITLE
Fix CSS filter help message

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/issues/7014#issuecomment-2531610211

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Tywele** [comment]
I'm still confused about this change:
grafik

Why did you remove the dots before the classnames? This way they don't properly represent CSS selectors anymore IMO. I think a much better hint would be something like `.footer, .header, div, #adbanner, p[data-sanitized-class~="menu"]` to show that pretty much all CSS selectors and additionally special syntax unique to FreshRSS also works.

**Comment by Frenzie** [comment]
`footer` selects `<footer>`, `.footer` selects `class=footer`. Both are valid selectors.

**Comment by Alkarex** [comment]
We could though add again an example of class selector like `.content`, maybe instead of `footer` which is a bit redundant since we already have `aside` in this example. PR welcome

**Comment by Frenzie** [comment]
Agreed, something like `.content` or `.entry-content` sounds like a good example.

**Comment by Tywele** [comment]
> `footer` selects `<footer>`, `.footer` selects `class=footer`. Both are valid selectors.

Yes I know I just couldn't think of a common class name in articles and instead used `div` as an element selector 😅 
And the current hint only represents element selectors and the special syntax and no class or id selectors which is what I was trying to say with my comment.

**Pull request merged**
