### PR TITLE
Update i18n/zh-cn

### PR DESCRIPTION
**Pull request by aidistan**
### Changes proposed in this pull request:

Update translation for zh-cn

### How to test the feature manually:

Browse each webpage

### Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks @aidistan and welcome 👍🏻 
I have merged a few more features, so if you can, there are a few more todos that have just arrived in this branch :-)
(Check for `// TODO` and `// DIRTY`)
Please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md

**Review by Alkarex — APPROVED** [review]

**Comment by aidistan** [comment]
@Alkarex Done. I like the `HTML + XPath (Web scraping)` way soooo much. Hope it get published ASAP : )

**Comment by Alkarex** [comment]
> @Alkarex Done. I like the `HTML + XPath (Web scraping)` way soooo much. Hope it get published ASAP : )

It is already in our edge branch (which is our continuous release, available via git, Docker) so feel free to give it a try already (we need testers), and I am working on publishing version 1.20.0 soon :-)

**Comment by aidistan** [comment]
Got it. Just changed the docker image from `:latest` to `:edge`.

**Comment by Alkarex** [comment]
A new Docker edge image has just arrived with your changes

**Pull request merged**
