### PR TITLE
Fix: Ansum theme cleaning

### PR DESCRIPTION
**Pull request by math-GH**
Almost similar to #4491

Most visible change: The login/register form.

Before:
grafik

After:
grafik

Changes proposed in this pull request:

- (S)CSS
- icons

How to test the feature manually:

use Ansum theme

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by math-GH** [comment]
@Alkarex Wow, that was the fasted PR "review" ;)

**Comment by Alkarex** [comment]
:-D

**Comment by Alwaysin** [comment]
Thanks @math-GH, you make me rediscovering all the themes :+1:

Not really specific to this one but it feels even "odder" with it, is the label page when you don't have any:
chrome_2022-08-25_22-08-42
Maybe there should be some logic to not display the "rename" and "delete" parts when there is no label. Also, in the URL it is called "tag" but then everywhere else it's "labels" but that's another story 😅 

Something else that strikes me as odd is that h1 and h2 titles look very similar.

**Comment by math-GH** [comment]
@Alwaysin let us discuss this in #4545

**Pull request merged**
