### PR TITLE
Fix slider views

### PR DESCRIPTION
**Pull request by Alkarex**
And fix full-page view of category configuration.
Fix https://github.com/FreshRSS/FreshRSS/pull/5449#issuecomment-1590021947

### CODE REVIEW

**Comment by math-GH** [comment]
While you are fixing also other sliders, please fix these too:
- user queries
- manage users

**Comment by Alkarex** [comment]
> While you are fixing also other sliders, please fix these too:
> 
>     * user queries
> 
>     * manage users

@math-GH Done in https://github.com/FreshRSS/FreshRSS/pull/5469/commits/bffb19580c9e7693028e259679fa10d72e1f9b3b

**Comment by Alkarex** [comment]
Merged as I will be using it this afternoon for a little project, but feedback still welcome

**Comment by math-GH** [comment]
Checked it. Looks good for me

**Pull request merged**
