### PR TITLE
Allow deep link to extension configuration

### PR DESCRIPTION
**Pull request by Alkarex**
Allow a full screen view of an extension configuration, with a deep-link URL.
Example:
image

Background: I have a use-case for which I need to provide a direct link to an extension configuration page.

### CODE REVIEW

**Comment by Alkarex** [comment]
For those working with extensions, could you please double-check that it does not break your use-cases?

**Comment by math-GH** [comment]
There is a bug:
1. go to extension config page
2. open the settings of a extension, f.e. CustomCSS (the slider will be opened)
3. save the settings

expected: the slider will be shown as slider or closed.
What is visible: The settings will be opened in full screen

**Comment by Alkarex** [comment]
What about now @math-GH ?

**Review by ColonelMoutarde — APPROVED** [review]

**Review by math-GH — APPROVED** [review]

**Comment by math-GH** [comment]
Additional question:
If you open the config in a new tab, than the new tab has no navigation on the left hand side. Is it on purpose?
Compared to the feed configuration, where the left navigation is given in a new tab

**Comment by Alkarex** [comment]
> Additional question:
> If you open the config in a new tab, than the new tab has no navigation on the left hand side. Is it on purpose?
> Compared to the feed configuration, where the left navigation is given in a new tab

No, good point, it was not on purpose

**Comment by Alkarex** [comment]
@math-GH Done https://github.com/FreshRSS/FreshRSS/pull/5449/commits/d546aff5bc52a62ff3cc8e92f80e49af5b7bd476

**Comment by math-GH** [comment]
Please double check: Does it make sense in the "full screen mode" (extension configs in new tab opened), that the config page will no be closed, when clicking the submit button?

**Comment by Alkarex** [comment]
> Does it make sense in the "full screen mode" (extension configs in new tab opened), that the config page will no be closed, when clicking the submit button?

Do you mean automatically closing the window/tab (if so, then no: in my case, it is the main window, not a new tab; and in other cases, I only think this should be done for modal windows, not tabs), or redirecting to another page after submission (if so, I do not really mind, but I find it fine as it is now)

**Comment by math-GH** [comment]
fine for me too

**Comment by math-GH** [comment]
@Alkarex I found one thing after it was merged: The `<title>` is just the default `FreshRSS`. It would be better to have the title of the extension in the tab.

**Comment by Alkarex** [comment]
> @Alkarex I found one thing after it was merged: The `<title>` is just the default `FreshRSS`. It would be better to have the title of the extension in the tab.

Done in https://github.com/FreshRSS/FreshRSS/pull/5469

**Pull request merged**
