### PR TITLE
Update dark theme css to lower brightness to all icons

### PR DESCRIPTION
**Pull request by Alwaysin**
Some elements had lower brightness already like sites favicons, but it felt off to have the checkbox, nav icons, etc to have full brightness and was hurting my eyes ^^'

### CODE REVIEW

**Comment by Alwaysin** [comment]
P.S.: this makes sense only when having ```'icons_as_emojis' => true``` in the user config.

**Comment by math-GH** [comment]
I do not understand what is your issue and what is your goal.

Your PR right now has this result:
Before: The help icon is darker
grafik

AfteR: The help icon is lighter
grafik

Because of the rules in frss.css

**Comment by Alwaysin** [comment]
As I've said, you need the special parameter in your user config file to see the thing.

Before:

image

After:

image

The emojis are hurting the eyes when you're in a completely dark room.

I've removed p.help cause I couldn't find where it was and thought it was unused, but we could put it back there, just adding the .icon alone.

**Comment by Alkarex** [comment]
All good @math-GH ?

**Review by math-GH — APPROVED** [review]

**Pull request merged**
