### PR TITLE
Add Fluent Reader Lite

### LINKED ISSUE #3418: Update information about Fluent Reader Lite
Currently Fluent Reader ([from v0.9.0 Beta](https://github.com/yang991178/fluent-reader-lite/releases)) supports Google Reader API

Also it have [android/ios](https://github.com/yang991178/fluent-reader-lite) platform 

Currently I use FreshRSS through Fluent Reader on my mac/ios and it seems stable (but I had some crashes on iOS, so maybe it more beta version)

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/3418

* https://hyliu.me/fluent-reader-lite/
* https://github.com/yang991178/fluent-reader-lite

### CODE REVIEW

**Comment by Alkarex** [comment]
https://github.com/yang991178/fluent-reader-lite/pull/77

**Comment by gingerbeardman** [comment]
I cannot get this app to work on iOS (or their non-Lite Mac desktop version).

Error: "Last sync failed at <d/m t>"

I have confirmed login details are correct. The iOS app does not give me any feedback when I enter login information. The Mac app says it's incorrect (but it's confirmed as correct) so I must be missing something.

**Comment by gingerbeardman** [comment]
Edit: I can login using Fever API url, but not Google Reader.

**Comment by gingerbeardman** [comment]
Edit: I can login using Fever API url, but not Google Reader url.

Edit: OK! it needs to be the full Google Reader URL https://demo.freshrss.org/api/greader.php

**Pull request merged**
