### PR TITLE
Fix update git version

### LINKED ISSUE #6512: The update process has encountered an error: Git error: Error 129 git not found: Please update manually!
### Describe the bug

A few days ago, I stumbled upon this issue.
From the backend of FreshRSS => Settings => Update, I see an update as in the image below:

sshot_2024-05-29_19 12 45

After clicking on the button "Update," I receive the error message as in the image below:

sshot_2024-05-29_19 12 58

Specifically, the error message says, "_The update process has encountered an error: Git error: Error 129 git not found: Please update manually!_"

### To Reproduce

On the server side, I go under `/usr/share/FreshRSS` and run `git pull`, and the response is `Already up to date.`

### Expected behavior

I expect the update from the backend. 

### FreshRSS version

1.24.0

### Environment information

- Database version: mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
- PHP version: PHP 8.2.19 (cli) (built: May 23 2024 12:34:42) (NTS)
- Installation type: manual install
-Web server type: nginx
- OS: Ubuntu 22.04.4 LTS
- Browser: Firefox

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/6512
Compatibility with git older than 2.37

### CODE REVIEW

**Comment by Alkarex** [comment]
Improvement of https://github.com/FreshRSS/FreshRSS/pull/6496

**Comment by i300220** [comment]
Tested 1.24.1 and it does display a better message:

`La mise à jour a rencontré un problème : Git error: Error 128 during git symbolic-ref: Reapply `chown www-data:www-data -R /var/www/sites/FreshRSS-git` or git pull manually! ["git version 2.39.2","fatal: detected dubious ownership in repository at '/var/www/sites/FreshRSS-git'","To add an exception for this directory, call:","","\tgit config --global --add safe.directory /var/www/sites/FreshRSS-git"] `

`Git error: Error 128 during git symbolic-ref: Reapply `chown www-data:www-data -R /var/www/sites/FreshRSS-git` or git pull manually! ["git version 2.39.2","fatal: detected dubious ownership in repository at '/var/www/sites/FreshRSS-git'","To add an exception for this directory, call:","","\tgit config --global --add safe.directory /var/www/sites/FreshRSS-git"] `

I did `git config --global --add safe.directory /var/www/sites/FreshRSS-git` and retried the upgrade button:  no effect, same error.

**Comment by Alkarex** [comment]
Ok, now at least you have the explanation and the solution in the message.
Have you tried the proposed solution? `chown www-data:www-data -R /var/www/sites/FreshRSS-git`

Your `git config` stuff was probably done with the wrong user.

All seems as it should be here.

**Comment by i300220** [comment]
Hi,

According to my history, I tried the git config thing as user and as root several times since 1.22
Zero effect whatsoever

```
 5530  sudo git config --global --add safe.directory /var/www/sites/FreshRSS-git
 8770  sudo git config --global --add safe.directory /var/www/sites/FreshRSS-git
 8785  sudo git config --global --add safe.directory /var/www/sites/FreshRSS-git
 9001  git config --global --add safe.directory /var/www/sites/FreshRSS-git
```
I did try `chown www-data:www-data -R /var/www/sites/FreshRSS-git/.git` and that didn't help.

`chown www-data:www-data -R /var/www/sites/FreshRSS-git` will be my next experiment.

I usually put everything from github in /usr/local/src, owned by root.  Something under /var/www is unusual and new for me so I need time to adapt.  Every other site is owned by me so 'git pull' does the thing.  Will manage...

Thanks again, it's a wonderful piece of software you wrote there.  I was so tired of Feedly changing the rules every now and then!

**Comment by Alkarex** [comment]
> tried the git config thing as user and as root

The needed user is `www-data` so not root, and not you. What git complains about is a mismatch about ownerships of various files

> it's a wonderful piece of software you wrote there

A pleasure to hear that :-)

**Comment by i300220** [comment]
> The needed user is `www-data`

I confirm that fixed the issue.  Upgrading to 1.24.3 worked without any problem for the very first time.  I guess it's the result of mixing 3 installation/upgrading methods from 2 different branches.

@Alkarex  Thanks for your help

**Pull request merged**
