### PR TITLE
Add archive.org as sharing service

### PR DESCRIPTION
**Pull request by yzqzss**
Changes proposed in this pull request:

- add archive.org as sharing service

How to test the feature manually:

1. share an article.
2. wait ten seconds. (The waiting time will be longer when the Internet Archive is overloaded)
3. automatically redirect to the snapshot URL.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

### CODE REVIEW

**Review by math-GH — APPROVED** [review]

**Comment by yzqzss** [comment]
_Merging is blocked: The base branch requires all commits to be signed_

Do I need to remake the PR?

**Review by Frenzie — APPROVED** [review]
Let's wait to see what @Alkarex says.

**Comment by Alkarex** [comment]
It is nice if all commits are signed (you can check GitHub documentation on how to do that) but we can merge nevertheless.
My connectivity is very poor at the moment. Did you have a chance to check the functionality @Frenzie ?

**Comment by Frenzie** [comment]
@Alkarex The link is (probably) fine, yes.

image

I can't speak as to the Internet Archive. I guess it must be overloaded. Minutes and counting. :-)

Edit: it just came back with a job failed, fwiw. `https://web.archive.org/save/https://smashingmagazine.com/2022/12/taking-stress-out-design-system-management/`

**Comment by math-GH** [comment]
I checked the functionality and it works fine.

**Pull request merged**
