### PR TITLE
Apache protect more non-public folders and files

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/discussions/6879#discussioncomment-10906338

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Alkarex** [comment]
@Frenzie I have added another rule for the root https://github.com/FreshRSS/FreshRSS/pull/6881/commits/087668e042d69ae78804b7fb8083f50d304ced0d

**Comment by Frenzie** [comment]
Could that interfere with updates? (Or risk losing customizations.) It might be better as a sample file akin to the constants.

**Comment by Alkarex** [comment]
> Could that interfere with updates? (Or risk losing customizations.)

What scenario could it be, do you believe?

> It might be better as a sample file akin to the constants.

I would rather have something that is a bit more secure out of the box, if possible

**Comment by Frenzie** [comment]
> What scenario could it be, do you believe?

For example a mod_rewrite on shared hosting as per the issue that prompted this PR, HTTP authentication, custom mimetypes, enabling compression, or dozens of other things neither of us can think of off the cuff. You don't want such customizations to get in the way of an upgrade or risk of being overwritten.

**Comment by Alkarex** [comment]
Right, so a case when users have a custom `./FreshRSS/.htaccess` ?

That is a good point.

By the way, the place for a custom `.htaccess` related to HTTP authentication is `./FreshRSS/p/i/.htaccess`

**Comment by Frenzie** [comment]
> Right, so a case when users have a custom ./FreshRSS/.htaccess ?

Yes, a similar problem theoretically exists anywhere but only for the root does it strike me as potentially problematic.

**Review by Frenzie — APPROVED** [review]

**Comment by Alkarex** [comment]
OIDC regression fixed in https://github.com/FreshRSS/FreshRSS/pull/6893

**Comment by Alkarex** [comment]
Reworked in https://github.com/FreshRSS/FreshRSS/pull/7008

**Pull request merged**
