### PR TITLE
Fix: article footer + improve: labeling

### PR DESCRIPTION
**Pull request by math-GH**
## Before:
grafik

grafik

## After:
(1), (2), (3): the icon is now clickable. It opens the dropdown menu
(3): new icon. (before: UTF8 icon, after: SVG icon)
(4): headline plus manage button added
(4): new label: UX improved. Button added. Adding by press Enter. Checkbox invisible
grafik

grafik

 Changes proposed in this pull request:

- Javascript + CSS
- new icon

How to test the feature manually:

1. go to footer of article
2. open "sharing" while clicking on the icon
3. open "article tags" while clicking on the icon
4. open "My labels" while clicking on the icon
5. add a new label by pressing enter
6. add a new label by pressing the button
7. click the manage button to go to label management

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
Sorry for the delay. Looks great 👍🏻 
Minor detail: on some themes, the add button's layout is a bit strange. For instance:

On "Pafat", a bit too close to the scrollbar
image

On "Mapco" + "Ansum", colour problems?
image

**Comment by math-GH** [comment]
@Alkarex Thanks. I fixed it.

Ready for more reviews

**Comment by Alkarex** [comment]
Looks good 👍🏻 

Not from that PR, but I have just noticed an extra padding-left in the tags for e.g. Mapco:
image

**Comment by math-GH** [comment]
> Not from that PR, but I have just noticed an extra padding-left in the tags for e.g. Mapco

The article tags will be changed with #4101

**Comment by Alkarex** [comment]
> The article tags will be changed with #4101

I have just tried and it does not seem to make any difference

**Comment by math-GH** [comment]
> > The article tags will be changed with #4101
> 
> I have just tried and it does not seem to make any difference

upps, you are right. The tag list is still available

**Pull request merged**
