### PR TITLE
Windows: release SQLite

### LINKED ISSUE #3970: [BUG] errors on page: delete my user account
**Describe the bug**
Error 1:
User: non-admin user
Page: Profil
Error: JavaScript error
How to reproduce: just load the page. Nothing to do

grafik

Error 2:
User: non-admin user
Page: Profil
Error: cannot delete my account

Sub error 2.1: with wrong password: no message, that the password is wrong
Sub error 2.2: with correct password: no message. just reloads the page.

**Environment information (please complete the following information):**
- Browser:  Firefox 93
- FreshRSS version: 1.19.0-dev (did not check 1.18.1)
- Installation type: web server (on XAMP Error 3 throws a 404 error page)

### LINKED ISSUE #6275: [Bug] User deleting: notification "User cannot be deleted"
### Describe the bug

The user "newUser" was deleted by the admin.
But a red notification "User newUser cannot be deleted" is shown.
But the user "newUser" is disappeared from the user list.
grafik

But the folder "data/newUser" is still available.

grafik

php_error_log:
```
[08-Apr-2024 16:31:06 Europe/Berlin] PHP Warning:  unlink(.../data\users\newUser/db.sqlite): Resource temporarily unavailable in ...\lib\lib_rss.php on line 892
[08-Apr-2024 16:31:06 Europe/Berlin] PHP Warning:  rmdir(.../data\users\newUser): Directory not empty in ...\lib\lib_rss.php on line 896

```

### To Reproduce

1. Go to 'user management'
2. delete a user

### Expected behavior

If the user cannot be deleted, then I expect to have the account still in the list.

### FreshRSS version

1.23.2-dev (latest)

### Environment information

- Database version: SQLite
- PHP version: PHP8.0
- Installation type: XAMP stack
-Web server type: Apache

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/3970
fix https://github.com/FreshRSS/FreshRSS/issues/6275

### CODE REVIEW

**Comment by Alkarex** [comment]
@math-GH I do not have a Windows native dev setup ready (I mostly use WSL when on Windows), but maybe you could try a bit more along the lines of this PR?

**Comment by math-GH** [comment]
I tested but it does not fix the bugs :/

**Comment by Alkarex** [comment]
Do you experience the same bug from the CLI?

**Comment by math-GH** [comment]
> Do you experience the same bug from the CLI?

I have never used the CLI but the i18n tool 🙄

**Comment by Alkarex** [comment]
```sh
./cli/delete-user.php --user username
```

https://github.com/FreshRSS/FreshRSS/blob/edge/cli/README.md

**Comment by math-GH** [comment]
Same error on CLI. `edge` and this PR have the same error messages.

**Comment by Alkarex** [comment]
@math-GH Please try again

**Comment by math-GH** [comment]
It works fine now. It deletes the directory in user data directory without error messages.

**Pull request merged**
