### PR TITLE
New feed mode: HTML + XPath + JSON dot notation (JSON in HTML)

### PR DESCRIPTION
**Pull request by Alkarex**
Same as `JSON+DotNotation` but first extracting the JSON string from an HTML document thanks to an XPath expression.
Example: `//script[@type='application/json']`
fix https://github.com/FreshRSS/FreshRSS/discussions/6876

### CODE REVIEW

**Comment by Alkarex** [comment]
Example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<opml xmlns:frss="https://freshrss.org/opml" version="2.0">
	<head>
		<title>FreshRSS</title>
		<dateCreated>Sat, 12 Oct 2024 19:54:23 +0200</dateCreated>
	</head>
	<body>
		<outline text="brussels" type="HTML+XPath+JSON+DotNotation"
			xmlUrl="https://environnement.brussels/offres-emploi"
			htmlUrl="https://environnement.brussels/offres-emploi"
			description="Flux RSS de brussels"
			frss:xPathToJson="normalize-space(//vacancy-overview/@*[name()=':items'])"
			frss:jsonItem="$"
			frss:jsonItemTitle="title"
			frss:jsonItemContent="summary"
			frss:jsonItemUri="link"
			frss:jsonItemCategories="degrees"
			frss:jsonItemUid="link"
		/>
	</body>
</opml>
```

image

**Review by Frenzie — APPROVED** [review]

**Comment by Alkarex** [comment]
~~I lack a little JavaScript detail to show/hide the new field depending on the mode~~
Edit: done

**Comment by Alkarex** [comment]
Ping @Fluidetom

**Comment by Alkarex** [comment]
Minor breaking change in https://github.com/FreshRSS/FreshRSS/pull/7369
Tests welcome.
Require explicit casting to string like `normalize-space(//vacancy-overview/@*[name()=':items'])` when targetting a single JSON, in order to support cases when there are multiple JSON fragments

**Pull request merged**
