### PR TITLE
Fix regression on header size due to padding

### PR DESCRIPTION
**Pull request by nicofrand**
Changes proposed in this pull request:

- Fix a regression on the origine-compact theme after https://github.com/FreshRSS/FreshRSS/commit/9621ab17479425845e66c2533817e6dcfe20feec#diff-892599b0ad323507d983e1465de5959f0008f4b38fc5f0b2afd196f487f2fd93 : the window now has a vertical scrollbar because the header is bigger than the expected 40px due to an unexpected padding (`.header > .item.title` having precedence on `.header > .item`.

How to test the feature manually:

1.
2.
3.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by math-GH** [comment]
I do not understand the issue. Could you please support with a screenshot?

**Comment by nicofrand** [comment]
On origin-compact there is a vertical scrollbars because the header now 
takes 40px + the padding on .item-title instead of just 40px.

**Comment by math-GH** [comment]
I optimized it a bit. Could you please check the result?

**Comment by Alwaysin** [comment]
Once again a discrepancy in zoom level on Windows I guess beacause I don't see the issue. This commit only makes the header a bit less compact to me (it does not bother me at all).

**Comment by nicofrand** [comment]
I am not zooming nor using Windows…

See: 

image

**Comment by nicofrand** [comment]
> I optimized it a bit. Could you please check the result?

That's not good, this needs to be applied on .item too (not only configure but search).

**Comment by math-GH** [comment]
let's step one behind.
I see an issue, that a clear bug description is missed.

Let me do it:
----------------

Affected theme: Origine compact theme

FreshRSS version: 1.20.1

Current behavior:
The header is higher than 40px
grafik

That leads to a always visible scrollbar, because the `#global` calculates with 40px from header.
grafik


Expected behavior:
Header height = 40px
No scrollbar, when it is not needed

**Comment by nicofrand** [comment]
OK I'll take that one but I am not the one who amended the merge request. 
The fix I provided works fine.

**Comment by math-GH** [comment]
Now it should work fine. I forget yesterday to use advantage of the optimization.

**Comment by math-GH** [comment]
> OK I'll take that one but I am not the one who amended the merge request. The fix I provided works fine.

I am happy that you found this issue and provided a fix that worked in general. Thanks for your contribution.

While I checked your PR I saw some basic issues that came from the Origine theme and made the fix of Origine compact theme a bit less clear. And I saw, that header height = 40px was missed.

Now the issue should be solved on the root

**Pull request merged**
