### PR TITLE
Change .onclick handlers to addEventlistener 

### PR DESCRIPTION
**Pull request by math-GH**
Reference #3903

Changes proposed in this pull request:

- Change .onclick handlers to addEventlistener 

Pull request checklist:

- [x] clear commit messages

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Not strictly close, but presumably the bulk of it. 

> There are others like .onerror.

**Comment by Alkarex** [comment]
Some clicks do not seem to work. I will try to check.

**Review by Alkarex — CHANGES_REQUESTED** [review]
Many events are not working, e.g. mark article as read/unread/favourite The two syntaxes are not exactly synonymous and do not have the same behaviour when it comes to e.g., propagation and bubbling of events. I cannot check in details now, but I believe additional lines are needed to cancel default events. I am not sure it is worth the extra complexity. Either mark as draft or reject this PR.

**Comment by math-GH** [comment]
will wait for #3950, maybe that could be also a root of problems

**Comment by math-GH** [comment]
The difference: https://www.geeksforgeeks.org/difference-between-addeventlistener-and-onclick-in-javascript/

**Comment by Alkarex** [comment]
Some of the bugs might be fixed with the third parameter `useCapture: true` https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener

**Comment by math-GH** [comment]
I will close this PR. It is too difficult to replace it and it works.

**Pull request closed without merging**
