### PR TITLE
Fix phpstan level 9 error for f.php

### PR DESCRIPTION
**Pull request by ColonelMoutarde**
Changes proposed in this pull request:

- Fix phpstan level 9 error

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
This PR does not seem to be sufficient to make this file pass PHPStan Level 9:

```console
$ vendor/bin/phpstan analyse --level 9 ./lib/favicons.php 
Note: Using configuration file /home/alex/GitHub/FreshRSS/phpstan.neon.
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------------------------------------------------------ 
  Line   favicons.php                                                                                    
 ------ ------------------------------------------------------------------------------------------------ 
  :16    Parameter #1 $finfo of function finfo_buffer expects finfo, finfo|false given.                  
  :16    Parameter #1 $haystack of function strpos expects string, string|false given.                   
  :17    Parameter #1 $finfo of function finfo_close expects finfo, finfo|false given.                   
  :32    Parameter #1 $handle of function curl_setopt_array expects CurlHandle, CurlHandle|false given.  
  :40    Parameter #1 $handle of function curl_setopt_array expects CurlHandle, CurlHandle|false given.  
  :41    Parameter #1 $handle of function curl_exec expects CurlHandle, CurlHandle|false given.          
  :42    Parameter #1 $handle of function curl_getinfo expects CurlHandle, CurlHandle|false given.       
  :43    Parameter #1 $handle of function curl_close expects CurlHandle, CurlHandle|false given.         
  :50    Function downloadHttp() should return string but returns bool|string.                           
 ------ ------------------------------------------------------------------------------------------------ 


                                                                                                                        
 [ERROR] Found 9 errors
```

**Comment by Alkarex** [comment]
P.S. Although nice, we are not quite there to fix Level 9 errors just yet.
Before that, we should focus on Level 6 https://github.com/FreshRSS/FreshRSS/issues/4112

**Review by Alkarex — CHANGES_REQUESTED** [review]
Make the whole file pass the claimed level

**Comment by ColonelMoutarde** [comment]
done

**Comment by Alkarex** [comment]
Sorry, it is me who read wrongly. Your first version did make `f.php` pass Level 9 already. Now even better with `./lib/favicons.php` as well...

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
There is now a list of files **not** passing Level 6 https://github.com/FreshRSS/FreshRSS/blob/edge/tests/phpstan-next.txt , with automatic tests.
When the list is all done, we will repopulate it for Level 7, and so on.
We cannot make a file really pass Level 9 when it has interdependencies with the rest of the codebase that is still missing many types (Level 6).

**Pull request merged**
