### PR TITLE
Improved: Pafat theme with vars

### PR DESCRIPTION
**Pull request by math-GH**
Ref. #4642
And similar to the other PRs that converted the themes to use the vars

Changes proposed in this pull request:

- CSS

How to test the feature manually:

1. Use Pafat theme

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Alkarex** [comment]
Looks good 👍🏻 

Is it on purpose that articles' background is now grey instead of white?

image

P.S. The purple colour of hovered links is also a bit strange (although not a problem)

**Comment by Alkarex** [comment]
P.P.S: I like the little triangle to indicating the active category 👍🏻 

image

**Comment by Alkarex** [comment]
Regarding the article background and the first-line background when hovering, I found it more natural when they were the same.

Before:

image

**Comment by math-GH** [comment]
Thanks for your feedback. I improved/fixed it. Could you please check?

**Pull request merged**
