### PR TITLE
UPDATE: Spanish translations 🇪🇸🇲🇽 [i18n] #4656

### LINKED ISSUE #4656: [i18n] Translation Spanish (ES)  🇪🇸🇲🇽  - Hacktoberfest Task
Dear Hacktoberfest-Community,

please help us to improve our 🇪🇸🇲🇽 Spanish translations.

While we develop our [FreshRSS ](https://freshrss.org/) app we cannot support the translations in all 15+ languages. 

## About the FreshRSS app
FreshRSS is a free, self-hostable feed aggregator licenced by [GNU3.0](https://github.com/FreshRSS/FreshRSS/blob/edge/LICENSE.txt). These days we celebrate the 10th birthday!

## Actual Status
Right now about 90% of our text is translated into Spanish.

## How to support us
How to do it:
1) it is very simple
2) all files are stored in `https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/es` ([Link](https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/es))
3) each untranslated text has an inline comment `//  TODO`
4) When the text is translated, just delete the comment
5) If the English term fits as well, please change the comment from `//  TODO` to `//  IGNORE`
6) open a Pull Request and link to this ticket

## Thanks
Thanks a lot. It will help our very international community of users and developers. Your submitted PRs will be published with our next release version 1.20.1 or 1.21.0

### PR DESCRIPTION
**Pull request by SoldierCorp**
Closes #4656

Update Spanish translations.

### CODE REVIEW

**Comment by Alkarex** [comment]
Thanks and welcome!
Please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md

**Comment by SoldierCorp** [comment]
Thanks @Alkarex !!

I’ll add my name to that file.

**Comment by marienfressinaud** [comment]
Hey @SoldierCorp, I'm just noticing you translated only the `admin.php` file, but there are more files with `TODO` ([gen.php](https://github.com/FreshRSS/FreshRSS/blob/edge/app/i18n/es/gen.php), [conf.php](https://github.com/FreshRSS/FreshRSS/blob/edge/app/i18n/es/conf.php) and [sub.php](https://github.com/FreshRSS/FreshRSS/blob/edge/app/i18n/es/sub.php)). Do you want to translate these last files as well? :)

**Comment by SoldierCorp** [comment]
@marienfressinaud Sure thing, I'll create another PR soon :)

Are you going to create another issue for it?

**Comment by marienfressinaud** [comment]
Thanks! I reopened https://github.com/FreshRSS/FreshRSS/issues/4656

**Pull request merged**
