### PR TITLE
Create "Authentik" specific OIDC configuration.

### LINKED ISSUE #5743: [BUG] Issue with OIDC (The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).)
**Describe the bug**
I've got an issue with OIDC and Authentik.
Each time I try to login, I receive the following error from Authentik : 
```
The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri).
```

The redirect URI I set in AUthentik is `https://mydomain.tld/i/oidc/`

And here is my Docker compose : 
```
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=longpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres/15/data:/var/lib/postgresql/data
    networks:
      - freshrss

  freshrss:
    image: freshrss/freshrss
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TZ=Europe/Paris
      - CRON_MIN=0,10,20,30,40,50
      - OIDC_ENABLED=1
      - OIDC_PROVIDER_METADATA_URL=https://myauthentik.tld/application/o/freshrss/.well-known/openid-configuration
      - OIDC_CLIENT_ID=client_id
      - OIDC_CLIENT_SECRET=client_secret
      - OIDC_X_FORWARDED_HEADERS=X-Forwarded-Port X-Forwarded-Proto X-Forwarded-Host
      - OIDC_SCOPES=openid email profile 

    volumes:
      - ./freshrss/data:/var/www/FreshRSS/data
      - ./freshrss/extensions:/var/www/FreshRSS/extensions
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`mydomain.tld`)
    networks:
      - web
      - freshrss

networks:
  web:
    name: web
    external: true
  freshrss:
```

**Expected behavior**
I should be redirected to FreshRSS home page

**Screenshots**
CleanShot 2023-10-25 at 18 00 35

**Environment information (please complete the following information):**
- Device: N.A
- OS: Docker
- Browser: Any
- FreshRSS version: 1.22.0
- Database version: Postgres 15

### PR DESCRIPTION
**Pull request by XtremeOwnageDotCom**
Just adding documentation specific to Authentik... or at least, a starting point.

There are a few todo items for which I don't know the anwser, however, the steps are valid.

Note- the ID/Secret listed here, is a dummy/fake.

I didn't include a change to actually reference this document.

Related issue: https://github.com/FreshRSS/FreshRSS/issues/5743

### CODE REVIEW

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
Thanks @XtremeOwnageDotCom 👍🏻 
Please double-check my changes

**Comment by Alkarex** [comment]
Please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md

**Comment by Alkarex** [comment]
The URL of the new documentation page is https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect-Authentik.html

**Comment by XtremeOwnageDotCom** [comment]
Apologies for the delay- Looks good. 

My only feedback, was noted here: https://github.com/FreshRSS/FreshRSS/issues/5743#issuecomment-1780058808

**Pull request merged**
