### PR TITLE
Dev updates with stylelint-stylistic

### LINKED ISSUE #5592: [BUG] .stylelintrc.json: deprecated instuctions
Stylelint version 15.0.0 ([published in February 2023](https://github.com/stylelint/stylelint/releases/tag/15.0.0)) marked some instructions as deprecated: https://stylelint.io/migration-guide/to-15

```
Deprecation warnings:
 - The "at-rule-name-space-after" rule is deprecated.
 - The "block-closing-brace-newline-after" rule is deprecated.
 - The "block-closing-brace-newline-before" rule is deprecated.
 - The "block-opening-brace-newline-after" rule is deprecated.
 - The "block-opening-brace-space-before" rule is deprecated.
 - The "color-hex-case" rule is deprecated.
 - The "declaration-colon-space-after" rule is deprecated.
 - The "declaration-colon-space-before" rule is deprecated.
 - The "no-eol-whitespace" rule is deprecated.
 - The "indentation" rule is deprecated.
```

Who wants to introduce Prettier?

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/5592

### CODE REVIEW

**Comment by math-GH** [comment]
After `npm update` I get this warning:
```
Deprecation warnings:
 - The "scss/at-import-no-partial-leading-underscore" rule is deprecated.
 - 'at-import-no-partial-leading-underscore' has been deprecated, and will be removed in '6.0'. Use 'load-no-partial-leading-underscore' instead. See: https://github.com/stylelint-scss/stylelint-scss/blob/v5.2.1/src/rules/at-import-no-partial-leading-underscore/README.md
```

But I cannot find where we use the `at-import-no-partial-leading-underscore` rule

**Comment by Alkarex** [comment]
> But I cannot find where we use the `at-import-no-partial-leading-underscore` rule

We do not directly. It is a sub-dependency.

**Comment by math-GH** [comment]
Do you have any idea how to fix it?

**Comment by Alkarex** [comment]
Wait till the dev dependencies gets updated, or propose a PR to https://github.com/stylelint-scss/stylelint-config-recommended-scss/issues/251

**Comment by Alkarex** [comment]
P.S. I am on it

**Comment by Alkarex** [comment]
https://github.com/stylelint-scss/stylelint-config-recommended-scss/pull/252

**Comment by Alkarex** [comment]
@math-GH Please try to replace in our `package.json`:

```json
"stylelint-config-recommended-scss": "git+https://github.com/Alkarex/stylelint-config-recommended-scss.git#load-no-partial-leading-underscore",
```

**Comment by Alkarex** [comment]
If you want @math-GH , we could even use my GitHub branch while waiting for the upstream merge

**Comment by math-GH** [comment]
> @math-GH Please try to replace in our `package.json`:
> 
> ```json
> "stylelint-config-recommended-scss": "git+https://github.com/Alkarex/stylelint-config-recommended-scss.git#load-no-partial-leading-underscore",
> ```

great, that helped and works fine

**Pull request merged**
