### PR TITLE
Code enchancement and typhinting

### PR DESCRIPTION
**Pull request by ColonelMoutarde**
Changes proposed in this pull request:

- Code enchancement and typhinting

Remarque:
- This class can be split in many classes with one responsibility by class (S.O.L.I.D).

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
While this is welcome, there are hundreds of missing type hints and we cannot address them in too many individual PRs, otherwise there is too much overhead in testing, etc. Adding type hints is not neutral and when added blindly can lead to severe regressions such as https://github.com/FreshRSS/FreshRSS/pull/4561#issuecomment-1315390980

So I suggest that when starting to address a file, we attempt to update the whole file, targetting at least [PHPStan level 6](https://phpstan.org/user-guide/rule-levels) in order to contribute efficiently to https://github.com/FreshRSS/FreshRSS/issues/4112 , or better still with higher levels up to 9 .

```console
$ make composer-test

$ vendor/bin/phpstan analyse --level 6 app/Models/Entry.php 
Note: Using configuration file /home/alexandre/GitHub/FreshRSS/phpstan.neon.
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------------------------------------------------------------------------------------ 
  Line   Entry.php                                                                                                                     
 ------ ------------------------------------------------------------------------------------------------------------------------------ 
  :20    Property FreshRSS_Entry::$title has no type specified.                                                                        
  :21    Property FreshRSS_Entry::$authors has no type specified.                                                                      
  :22    Property FreshRSS_Entry::$content has no type specified.                                                                      
  :23    Property FreshRSS_Entry::$link has no type specified.                                                                         
  :24    Property FreshRSS_Entry::$date has no type specified.                                                                         
  :25    Property FreshRSS_Entry::$date_added has no type specified.                                                                   
  :47    Property FreshRSS_Entry::$tags has no type specified.                                                                         
  :48    Property FreshRSS_Entry::$attributes has no type specified.                                                                   
  :50    Method FreshRSS_Entry::__construct() has parameter $pubdate with no type specified.                                           
  :114   Method FreshRSS_Entry::authors() has no return type specified.                                                                
  :129   Method FreshRSS_Entry::enclosureIsImage() has parameter $enclosure with no value type specified in iterable type array.       
         💡 See: https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-iterable-type                                     
  :302   Method FreshRSS_Entry::date() has no return type specified.                                                                   
  :313   Method FreshRSS_Entry::dateAdded() has no return type specified.                                                              
  :326   Method FreshRSS_Entry::isRead() has no return type specified.                                                                 
  :330   Method FreshRSS_Entry::isFavorite() has no return type specified.                                                             
  :349   Method FreshRSS_Entry::tags() has no return type specified.                                                                   
  :349   Method FreshRSS_Entry::tags() has parameter $asString with no type specified.                                                 
  :357   Method FreshRSS_Entry::attributes() has no return type specified.                                                             
  :357   Method FreshRSS_Entry::attributes() has parameter $key with no type specified.                                                
  :365   Method FreshRSS_Entry::_attributes() has no return type specified.                                                            
  :365   Method FreshRSS_Entry::_attributes() has parameter $value with no type specified.                                             
  :396   Method FreshRSS_Entry::_id() has parameter $value with no type specified.                                                     
  :424   Method FreshRSS_Entry::_authors() has parameter $value with no type specified.                                                
  :448   Method FreshRSS_Entry::_date() has parameter $value with no type specified.                                                   
  :454   Method FreshRSS_Entry::_dateAdded() has parameter $value with no type specified.                                              
  :462   Method FreshRSS_Entry::_isRead() has parameter $value with no type specified.                                                 
  :466   Method FreshRSS_Entry::_isFavorite() has parameter $value with no type specified.                                             
  :482   Method FreshRSS_Entry::_tags() has parameter $value with no type specified.                                                   
  :605   Method FreshRSS_Entry::applyFilterActions() has no return type specified.                                                     
  :605   Method FreshRSS_Entry::applyFilterActions() has parameter $titlesAsRead with no value type specified in iterable type array.  
         💡 See: https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-iterable-type                                     
  :752   Method FreshRSS_Entry::toArray() return type has no value type specified in iterable type array.                              
         💡 See: https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-iterable-type                                     
 ------ ------------------------------------------------------------------------------------------------------------------------------ 


                                                                                                                        
 [ERROR] Found 31 errors
```


It is also good to check that the syntax works with our oldest supported PHP version, e.g.:

```sh
docker build --pull --tag freshrss/freshrss:oldest -f Docker/Dockerfile-Oldest .

docker run --rm -v $PWD:/var/www/FreshRSS freshrss/freshrss:oldest \
    sh -c "find . -type d -name 'vendor' -prune -o -name '*.php' -print0 | xargs -0 -n1 php -l 1>/dev/null"
```

**Comment by Alkarex** [comment]
Why did you close? It was a good start. Only with a number of relatively easy fixes missing

**Comment by ColonelMoutarde** [comment]
It’s a problème of « I.C.C. » in french « interface chaise clavier » 😅 the
Pr is reopen 😁
-- 
Cordialement,
Luc Sanchez

**Comment by Frenzie** [comment]
I believe that might be originally English. ;-) 

https://en.wiktionary.org/wiki/PEBCAK

**Comment by Alkarex** [comment]
Oh, is it closed again?

**Pull request closed without merging**
