### PR TITLE
favicon url change

### PR DESCRIPTION
**Pull request by BlueWhale235**
Changes proposed in this pull request:

-add favicons ext in url:
-rewriterule: f.php?xxx --> ico-xxx.ico

How to test the feature manually:

1. hosted by myself

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [x] documentation updated
---
Additional:
Because some CDN server cache static files by extension so i add it.

### CODE REVIEW

**Comment by Alkarex** [comment]
Hello,
Thanks for the PR. We need to support more than Apache though, so I cannot merge as it is.
Furthermore, there is some computational cost of using RewriteRule, so we would also need a compelling reason.
Is there any issue you are trying to solve with this patch? Maybe we could find another solution.

**Comment by Alkarex** [comment]
For the record, see https://httpd.apache.org/docs/current/mod/mod_proxy_html.html#proxyhtmlurlmap for dynamically changing the URLs in the HTML without having to change the PHP code

**Comment by BlueWhale235** [comment]
I haven't used `proxyhtmlurlmap`  so  i will search for its document and test.

**Comment by Alkarex** [comment]
Feel free to comment again (maybe a documentation entry with `proxyhtmlurlmap` if you find something useful), but otherwise closing for now

**Comment by BlueWhale235** [comment]
ok. Now I am busy because of a next week's examination.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexandre ***@***.***&gt;; 
发送时间: 2022年5月30日(星期一) 下午4:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FreshRSS/FreshRSS] favicon url change (PR #4361)





 
Closed #4361.
 
&mdash;

**Pull request closed without merging**
