### PR TITLE
[Feature - Hacktoberfest] - Add Admin transalation pt br 

### LINKED ISSUE #4660: [i18n] Translation Brazil Portuguese (PT_BR) 🇧🇷 - Hacktoberfest Task
Dear Hacktoberfest-Community,

please help us to improve our 🇧🇷 Brazil Portuguese translations.

While we develop our [FreshRSS ](https://freshrss.org/) app we cannot support the translations in all 15+ languages. 

## About the FreshRSS app
FreshRSS is a free, self-hostable feed aggregator licenced by [GNU3.0](https://github.com/FreshRSS/FreshRSS/blob/edge/LICENSE.txt). These days we celebrate the 10th birthday!

## Actual Status
Right now about 90% of our text is translated into 🇧🇷 Brazil Portuguese.

## How to support us
How to do it:
1) it is very simple
2) all files are stored in `https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/pt-br` ([Link](https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/pt-br))
3) each untranslated text has an inline comment `//  TODO`
4) When the text is translated, just delete the comment
5) If the English term fits as well, please change the comment from `//  TODO` to `//  IGNORE`
6) open a Pull Request and link to this ticket

## Thanks
Thanks a lot. It will help our very international community of users and developers. Your submitted PRs will be published with our next release version 1.20.1 or 1.21.0

### PR DESCRIPTION
**Pull request by NicolasPereira**
Closes #4660 

I'm sending the first contribution to the Brazilian Portuguese translation!
Soon I will open other PRs related to this Issue

Changes proposed in this pull request:

- Added the Brazilian Portuguese translations for the administrative part
-
-

How to test the feature manually:

1. Select Portuguese Brazilian lanaguage
2. Open Admin >>  Configuration System

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by math-GH** [comment]
You can also do the other files here into this PR :)

**Comment by NicolasPereira** [comment]
> You can also do the other files here into this PR :)

I didn't translate the other files, in case more Brazilians wanted to contribute.
In this way, I will add the other translations and go up in this PR

**Comment by math-GH** [comment]
Please go ahead. It is better to have a complete translation then waiting for other contributors ;)

**Comment by NicolasPereira** [comment]
@math-GH 
Done! I did all the translations

**Comment by math-GH** [comment]
Awesome. That is a great improvement for FreshRSS.

Please add yourself on our [Credits ](https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md) list :)

**Pull request merged**
