### PR TITLE
Improved: Origine theme (colors in vars)

### PR DESCRIPTION
**Pull request by math-GH**
Ref. #4642

grafik

Changes proposed in this pull request:

- CSS: colors in variables
- CSS: some little improvements

How to test the feature manually:

1. use Origine theme

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
There is quite number of differences. Are they on purpose? (e.g. logo position and size, colour of the red envelope in the button bar, top margin, borders...)

Before:

image


After:

image

P.S. The lines are again jumping a few pixels when hovering titles (observed with Origine, Pafat)

**Comment by math-GH** [comment]
> There is quite number of differences. Are they on purpose? (e.g. logo position and size, colour of the red envelope in the button bar, top margin, borders...)

Mostly, yes, it is on purpose.

Logo: it is now centered above the aside navigation. It is the same size as before.

Red envelope in the button bar: Here I need some feedback if you like it or not. 
Reason:
The buttons are in 3D style. When the button is activated then there is a inset shadow, because the button is deeper then the surface around. It would also mean that the logo is in the shadow, so it should be darker.
Maybe it is to dark here?

Top margin: Before it was 85px height, after: 64px. It is a trial if it would be "better" or not.

Borders has now a little brighter grey. In my opinion it looks fresher, than the grey borders before.

> P.S. The lines are again jumping a few pixels when hovering titles (observed with Origine, Pafat)

I cannot reproduce it with Origine.

**Comment by Alwaysin** [comment]
The lines are jumping for me also. It is doing it on Mapco also (not tested all the themes), but only in Chrome and not in Firefox for this theme. For origine and Pafat, it does it on both browsers.

**Comment by Alwaysin** [comment]
Weird. Going from 82c4a54f to 2dbd11bd improved the situation for Mapco. The two first titles are not jumping anymore. I double-checked:
```
# git checkout 82c4a54f
-> all titles are jumping on Chrome

# git checkout 2dbd11bd
-> two first and two last titles are not jumping!
```

EDIT: nailed down to d78c796 that is making the first two not jumping, if it can somehow make it easier to determine what the problem is.

**Comment by math-GH** [comment]
Please please keep the discussion in this PR only related to this PR (Origine theme). Mapco and Pafat were not touched here.

**Comment by math-GH** [comment]
Anything left todo for this PR?

**Comment by Alkarex** [comment]
It is very good to have the colours as variables, but I am not so found of some of the other changes such as the darker colour of the envelope. If anything, the change of darkness looks counter intuitive to me: I would expect a button to be more bright when it is active and darker when not active (and in this PR so far, it is the opposite).

If not too much work, maybe you could try to put those cosmetic changes in another PR so that we can merge this one and get some feedback.

**Comment by Alkarex** [comment]
P.S. It would be nice if we could fix the few outstanding UI / theme regressions so we can release 1.20.1, which contains some fixes I would like to publish soon (also for some other distributions such as YunoHost https://github.com/YunoHost-Apps/freshrss_ynh/pull/146#issuecomment-1275108172 ).

**Comment by math-GH** [comment]
> It is very good to have the colours as variables, but I am not so found of some of the other changes such as the darker colour of the envelope. If anything, the change of darkness looks counter intuitive to me: I would expect a button to be more bright when it is active and darker when not active (and in this PR so far, it is the opposite).
> 
> If not too much work, maybe you could try to put those cosmetic changes in another PR so that we can merge this one and get some feedback.

Improved. Please check

**Comment by Alwaysin** [comment]
And now origine-compact once again is not compact anymore...
I don't remember if there is an issue to be reopened instead of making a new one?

(But I like the new look and feel 👍 )

**Comment by Alkarex** [comment]
Please make a new one @Alwaysin and sorry I did not spot this regression before merging. We need to fix the few remaining UI regressions before releasing 1.20.1.

**Pull request merged**
