### PR TITLE
Update Russian Translation

### LINKED ISSUE #3898: [Improvement] i18n: upgrade our translations. 18 languages available
Dear community,

FreshRSS user interface is translated into 18 languages. Not all languages are covered by active developers.

Available languages:
- [ ] CZ: Czech (some phrases need a translation EN -> CZ) 🇨🇿
- [x] DE: German (active supported. 99.6% is translated) 🇩🇪🇦🇹🇨🇭
- [x] EN: British English (active supported. 100% is translated) 🇬🇧
- [x] EN_US: USA English (active supported. 100% is translated) 🇺🇸
- [x] ES: Spanish (some phrases need a translation EN -> ES) 🇪🇸🇲🇽
- [x] FR: French (active supported. 100% is translated) 🇫🇷
- [ ] HE: Hebrew (some phrases need a translation EN -> HE) 🇮🇱
- [ ] IT: Italian (some phrases need a translation EN -> IT) 🇮🇹
- [x] JA: Japanese (99% translated. Some less phrases need a translation EN -> JA)
- [x] KO: Korean (some phrases need a translation EN -> KO) 🇰🇷🇰🇵
- [x] NL: Dutch (active supported. 99.6% is translated)🇳🇱
- [x] OC: Occitan (some phrases need a translation EN -> OC)🇫🇷🇮🇹
- [x] PL: Polish (some phrases need a translation EN -> PL)🇵🇱
- [x] PT_BR: Brazil Portuguese  (99.9% done; one single missing translation EN -> PT_BR) 🇧🇷
- [x] RU: Russian (some phrases need a translation EN -> RU) 🇷🇺
- [x] SK: Slovakian (some phrases need a translation EN -> SK) 🇸🇰
- [ ] TR: Turkish (some phrases need a translation EN -> TR) 🇹🇷
- [x] ZH_CN: Chinese (some phrases need a translation EN -> ZH_CN)🇨🇳

The language files are PHP files in this folder: https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n

Do you miss your favorite language? Feel free to add it to our supported languages.

Please send us a Pull Request or use the comments below to improve the translations.

(Hacktoberfest participants are welcome to help)

### PR DESCRIPTION
**Pull request by id-konstantin-stepanov**
Closes #3898 

Changes proposed in this pull request:
- Update Russian Translation in https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n

Pull request checklist:
- [ х] clear commit messages
- [ х] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

### CODE REVIEW

**Review by aledeg — COMMENTED** [review]
For the _FreshRSS_ and _API_ translations, you should add them in the ignore file. Otherwise, next time we run the automated tools on the files, the @todo will be added again.

**Comment by id-konstantin-stepanov** [comment]
Add sub.php and gen.php in .gitignore. Hope this is correct.

**Comment by aledeg** [comment]
Looking at what you've done makes me realize that I didn't explain correctly what were my expectations.
Please remove the files from the _.gitignore_ file and add the translation keys in https://github.com/FreshRSS/FreshRSS/blob/edge/cli/i18n/ignore/ru.php. You can check its content and the content of the other files in the same folder to understand what I mean.
If you have any subsequent question, I'll answer you with pleasure.

**Comment by aledeg** [comment]
I've just noticed that it's your first contribution. Thank you for that! I hope to see you contribute regularly!

**Comment by id-konstantin-stepanov** [comment]
Thanks. Now it became clearer. I will be happy to help the development of the project further.

**Review by aledeg — APPROVED** [review]

**Comment by Alkarex** [comment]
Thanks @id-konstantin-stepanov and welcome!
If you can, there is a single remaining TODO for `'next_unread_article'`

**Review by Alkarex — APPROVED** [review]

**Comment by id-konstantin-stepanov** [comment]
Translate 'next_unread_article'.

**Comment by Alkarex** [comment]
Thanks!
Watch out, you have overiden one of my commits: https://github.com/FreshRSS/FreshRSS/commit/eac5c898c1a8e4ab3641196e7357aa8ed030feee
Generally, forced pushes should be avoided (risks of errors, breaks other people's checkouts, breaks GitHub's review systems, etc.).

**Comment by Alkarex** [comment]
@id-konstantin-stepanov Please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md :-)

**Pull request merged**
