### PR TITLE
fix: jumping lines

### LINKED ISSUE #4698: Regression: lines jumping
The lines are jumping for me also. It is doing it on Mapco also (not tested all the themes), but only in Chrome and not in Firefox for this theme. For origine and Pafat, it does it on both browsers.

_Originally posted by @Alwaysin in https://github.com/FreshRSS/FreshRSS/issues/4693#issuecomment-1270549717_

### PR DESCRIPTION
**Pull request by math-GH**
Closes #4698

Please check with Firefox and Chrome/Chromium.

Themes: Origine, Pafat and others.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alwaysin** [comment]
Doesn't work for me in Chrome and this PR makes origine-compact even worse.

**Comment by math-GH** [comment]
hopefully it is fixed now in all themes. I tested it in Chromium.

**Review by Alkarex — APPROVED** [review]

**Comment by Alwaysin** [comment]
In Chrome, on Origine and Pafat, it is still jumping every other article: the first one doesn't jump, the second one jumps, the third one doesn't, the fourth does,...
Mapco is more erratic: articles jumping are the 4th, the 7th, and straight to the 20th, 23rd,...

**Comment by math-GH** [comment]
I guess it is a calculation problem. Default-size of 16px, .flux use 0.9rem = 14.4px. The result is sometime a pixel above, some below.
It will not be the end of improvements. On my todo list is still a rewrite of the paddings and positions around text from `px` to `rem`. That is why I started the rewrite very early of next release. It need some time to rewrite. First I focused on using colors in variables and font-size and line-height in rem units. Work is left.

**Comment by Alkarex** [comment]
The issue is not fully solved, but let's merge this PR already to avoid further conflicts

**Pull request merged**
