### PR TITLE
Improve: new article banner

### PR DESCRIPTION
**Pull request by math-GH**
grafik

Changes proposed in this pull request:

- in theme "Origine" fixed: the blue box had a padding, so that not the whole box was clickable
- all themes: background change while hovering now assigned to the link, not to the box

How to test the feature manually:

1. hover with the mouse over the new article banner

Pull request checklist:

- [x ] clear commit messages
- [ x] code manually tested

### CODE REVIEW

**Comment by math-GH** [comment]
@Alkarex maybe it is worth for 1.19, because with this #3999 I see this blue banner much more often* than in 1.18 and I am annoyed often about the small click area.

*) I use the edge branch on my daily system to test it and enjoy the new functions

**Comment by math-GH** [comment]
@Alkarex @Frenzie Ready for 1.20 :)

**Review by Frenzie — APPROVED** [review]
lgtm, also looks good in mobile view?

**Comment by math-GH** [comment]
> lgtm, also looks good in mobile view?

Nothing visible changed. Just the :hover and the clickable area.

**Pull request merged**
