### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by martinrotter**
Sync in RSS Guard is now much faster, better (optional) syncing algorithm was implemented

Closes #

Changes proposed in this pull request:

-
-
-

How to test the feature manually:

1.
2.
3.

Pull request checklist:

- [ ] clear commit messages
- [ ] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by math-GH** [comment]
what stops us from merging?

**Comment by Alkarex** [comment]
I would like to give it a try myself, but got delayed. Alternatively, I would like to see a trace of the HTTP calls to check that the synchronisation is sane and deserves 3 stars

**Comment by Alkarex** [comment]
I have finally taken the time to test with https://github.com/martinrotter/rssguard/releases/tag/4.2.4 - sorry for the delay.

While the synchronisation is indeed better, it could still be improved.

In particular, it is using a sub-optimal POST call to `/reader/api/0/stream/items/contents?output=json&n=200000` with thousands of parameters of the form `i=tag%3Agoogle.com%2C2005%3Areader%2Fitem%2F0005d41f82ea742c&i=tag%3Agoogle.com%2C2005%3Areader%2Fitem%2F0005d8ac2ed99521&i=tag%3Agoogle.com%2C2005%3Areader%2Fitem%2F0005e114a6939bb9................` (continues for half a MB)

This leads to a warning: `PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini.`

As an alternative, see my recommendation for synchronisation : https://github.com/FreshRSS/FreshRSS/issues/2566#issuecomment-541317776

**Comment by Alkarex** [comment]
Let's go for 2⭐ for now :-)

**Comment by Alkarex** [comment]
@martinrotter Do not hesitate to ask if you would like to discuss or get some feedback on the synchronisation strategy

**Pull request merged**
