### PR TITLE
code improvement for phpstan and humans ;)

### PR DESCRIPTION
**Pull request by ColonelMoutarde**
Changes proposed in this pull request:

- code improvement for phpstan and humans ;)

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Review by Alkarex — CHANGES_REQUESTED** [review]
Please make sure to pass at least PHPStan level 6:

```console
$ vendor/bin/phpstan analyse --level 6 app/Models/Tag.php 
Note: Using configuration file /home/alexandre/GitHub/FreshRSS/phpstan.neon.
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ --------------------------------------------------------------------------------- 
  Line   Tag.php                                                                          
 ------ --------------------------------------------------------------------------------- 
  :8     Property FreshRSS_Tag::$name has no type specified.                              
  :9     Property FreshRSS_Tag::$attributes has no type specified.                        
  :10    Property FreshRSS_Tag::$nbEntries has no type specified.                         
  :11    Property FreshRSS_Tag::$nbUnread has no type specified.                          
  :21    Method FreshRSS_Tag::_id() has parameter $value with no type specified.          
  :36    Method FreshRSS_Tag::attributes() has parameter $key with no type specified.     
  :44    Method FreshRSS_Tag::_attributes() has parameter $key with no type specified.    
  :44    Method FreshRSS_Tag::_attributes() has parameter $value with no type specified.  
  :59    Method FreshRSS_Tag::nbEntries() has no return type specified.                   
  :67    Method FreshRSS_Tag::_nbEntries() has parameter $value with no type specified.   
  :82    Method FreshRSS_Tag::_nbUnread() has parameter $value with no type specified.    
 ------ --------------------------------------------------------------------------------- 


                                                                                                                        
 [ERROR] Found 11 errors
```

**Comment by Alkarex** [comment]
Good start. Please check same comment than https://github.com/FreshRSS/FreshRSS/pull/5030#issuecomment-1399317663

**Review by aledeg — APPROVED** [review]

**Comment by ColonelMoutarde** [comment]
pass PHPSTAN 5

**Comment by ColonelMoutarde** [comment]
Pass PHPStan Leve6

**Comment by Alkarex** [comment]
I have made it pass PHPStan level 9 https://github.com/FreshRSS/FreshRSS/pull/5084/commits/08fa965335c9c415f79e0a3ddf8d3c61b2fa6cb3

**Review by Alkarex — APPROVED** [review]

**Pull request merged**
