### PR TITLE
Improved: Important feeds icon: bell instead of pin

### PR DESCRIPTION
**Pull request by math-GH**
In #5782 we were looking for an icon for the important feeds section.

Here a draft for a bell icon instead of the pin icon

grafik

Changes proposed in this pull request:

- (TBD)
-
-

How to test the feature manually:

1. (TBD)
2.
3.

Pull request checklist:

- [ ] clear commit messages
- [ ] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by math-GH** [comment]
What do you think? Is the bell a better icon? Is it worth to change?

What me inspired to use the bell icon: some tools use the bell to highlight "important" messages

**Comment by Alkarex** [comment]
I like it, but I also like the current one, so I do not really mind :-)
On the negative side, it might lead some users to believe that there are special notifications there

**Comment by Frenzie** [comment]
The pin makes a bit more conceptual sense to me (you pinned them as important) while I associate the bell more with messages, but strictly visually speaking it looks decent enough.

**Comment by math-GH** [comment]
great. I agree.

**Pull request closed without merging**
