### PR TITLE
Update table of Android clients

### LINKED ISSUE #6382: native apps list: News+ is very out of time
News+ repository: https://github.com/noinnion/newsplus/

(Last code commit was 10 years ago. The repo seems to be unmaintained. See https://github.com/noinnion/newsplus/issues/107 too)

The [website](https://noinnion.com/newsplus/) itself is unusable, so I guess nobody is maintaining this.

I would suggest to be honest to the reader of our native apps list. We should not have this app on row number 1 on our list anymore.

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/6382

### CODE REVIEW

**Comment by Frenzie** [comment]
I realize you just archived EasyRSS, but it hasn't needed any changes in a decade,  version bump and forced recompilation due to F-Droid notwithstanding. :-)

**Comment by Alkarex** [comment]
> I realize you just archived EasyRSS, but it hasn't needed any changes in a decade, version bump and forced recompilation due to F-Droid notwithstanding. :-)

[Indeed](https://github.com/Alkarex/EasyRSS/), but I think [Readrops](https://github.com/readrops/Readrops) or [Capy Reader](https://github.com/jocmp/capyreader) are at least as good now, also available on F-Droid, and better maintained. Additional tests welcome

**Comment by Alkarex** [comment]
@javerous It does not look like the [GReader Redate extension](https://github.com/javerous/freshrss-greader-redate) is needed anymore, for instance for FeedMe. Additional tests welcome

**Comment by javerous** [comment]
Hi @Alkarex — thanks for notifying me. The extension was also needed for Reeder (now known as Reeder Classic) on macOS & iOS. Anything changed on FreshRSS side which would make it obsolete ? I can set up a new test if necessary, yes.

**Comment by Alkarex** [comment]
Yes please for the tests @javerous 
The text has been for a long time *No longer required for Reeder 5*

**Comment by javerous** [comment]
Ah yes, I see — https://github.com/FreshRSS/FreshRSS/commit/7ba3f0228dfff22a256712bdd70a8db56fbc14b9

And he even contacted me (and I answered…), but I totally forgot, I just continued to use Reeder 5 with the extension enabled… ! https://github.com/javerous/freshrss-greader-redate/issues/1

I will try to test tomorrow.

**Comment by Alkarex** [comment]
Merging to get wider feedback (sending the link to other people)

**Comment by javerous** [comment]
Okay, I tested Reeder 5 without my extension: everything seems to work fine. If there is no remaining client with the original issue, I will archive the extension.

Thanks !

**Comment by Alkarex** [comment]
@javerous Thanks for the feedback. I am also looking for help to update the [table of clients](https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps), in particular the iOS / macOS ones (I am just done with the Android ones).

**Comment by javerous** [comment]
I will try to take a look at that !

**Pull request merged**
