### PR TITLE
[i18n] Added Czech translation

### LINKED ISSUE #6318: [i18n] Translation Czech (CZ) 🇨🇿 needs translators
Dear FreshRSS-Community,

please help us to improve our Czech translations.

While the core developer and many other contributors develop our [FreshRSS ](https://freshrss.org/) app we cannot support the translations in all 20+ languages. 

## Actual Status
Right now about 90% of our text is translated into Czech.

## How to support us
How to do it:
1) it is very simple
2) all files are stored in `https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/cz` ([Link](https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/cz))
3) each untranslated text has an inline comment `//  TODO`
4) When the text is translated, just delete the comment
5) If the English term fits as well, please change the comment from `//  TODO` to `//  IGNORE`
6) open a Pull Request and link to this ticket

## Thanks
Thanks a lot. It will help our very international community of users and developers. Your submitted PRs will be published with our next release version [1.24.0](https://github.com/FreshRSS/FreshRSS/milestones) or later

### PR DESCRIPTION
**Pull request by MayMeow**
Closes #6318 

Changes proposed in this pull request:

- updated Czech  translation

How to test the feature manually:

1.
2.
3.

Pull request checklist:

- [ ] clear commit messages
- [ ] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by math-GH** [comment]
You can delete the `TODO` when it is translated. It is not needed to mark it with `DIRTY` if there are just "untranslatable words". 

`DIRTY` means: the entry has been translated but needs to be updated.

**Comment by MayMeow** [comment]
> You can delete the `TODO` when it is translated. It is not needed to mark it with `DIRTY` if there are just "untranslatable words".
> 
> `DIRTY` means: the entry has been translated but needs to be updated.

Kept it there until I have translate everything (it's easier to me when i go back to final check)... I have few more translations left anyway

**Comment by MayMeow** [comment]
Few things about that i dont know how or if to translate

- `dotted path`: Tečkovaná cesta (based on how we translate dotted line -> "Tečkovaná čára"
- `Payload`: Don't think this has some equivalent in I only know "užitočné zaťaženie" or "užitečné zatížení" for czech but we in company dont translate it... its just "payload"

**Comment by math-GH** [comment]
> Few things about that i dont know how or if to translate
> 
>     * `dotted path`: Tečkovaná cesta (based on how we translate dotted line -> "Tečkovaná čára"
 
`dotted path` is already renamed to `dot notation`, because it is the correct technical term for it. (That is the reason for the merge conflict. I can solve it for you if you want)
If there is no good translation then just keep the English term. I guess that most of people would understand it.

>     * `Payload`: Don't think this has some equivalent in I only know "užitočné zaťaženie" or "užitečné zatížení" for czech but we in company dont translate it... its just "payload"

That is ok. I did the same for the German translation and kept the English term

**Comment by MayMeow** [comment]
You can resolve this conflict

**Comment by math-GH** [comment]
fixed

**Pull request merged**
