### PR TITLE
Fixed peroid names in the Hungarian translation

### PR DESCRIPTION
**Pull request by andris155**
Changes proposed in this pull request:

- Fixed peroid names in the Hungarian translation

How to test the feature manually:

1. Go to Settings -> Display -> Language
2. Change language to Magyar/Hungarian and Submit.
3. Language is Hungarian with new translations and fixes.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]

**Comment by Alkarex** [comment]
Thanks!

**Comment by Alkarex** [comment]
P.S. It looks there is a single line lacking a translation in Hungarian :-)
https://github.com/FreshRSS/FreshRSS/blob/9dec2af35d99748b2251089a5e96932b50435254/app/i18n/hu/admin.php#L197

**Comment by Alkarex** [comment]
And congrats with PR number 6000 🎆

**Comment by andris155** [comment]
> P.S. It looks there is a single line lacking a translation in Hungarian :-)
> 
> https://github.com/FreshRSS/FreshRSS/blob/9dec2af35d99748b2251089a5e96932b50435254/app/i18n/hu/admin.php#L197

TODO is also written for this line in the English translation.  What is the final English translation that can be translated?

https://github.com/FreshRSS/FreshRSS/blob/edge/app/i18n/en/admin.php#L197

**Comment by Frenzie** [comment]
I suspect it only says todo because the documentation wasn't online yet at the time it was added.

**Comment by Alkarex** [comment]
The command line for adding new i18n strings also puts a TODO in the English version, which is sometimes forgotten afterwards. It is a mistake and should be stripped

**Pull request merged**
