### PR TITLE
fixes jumping lines

### LINKED ISSUE #4698: Regression: lines jumping
The lines are jumping for me also. It is doing it on Mapco also (not tested all the themes), but only in Chrome and not in Firefox for this theme. For origine and Pafat, it does it on both browsers.

_Originally posted by @Alwaysin in https://github.com/FreshRSS/FreshRSS/issues/4693#issuecomment-1270549717_

### PR DESCRIPTION
**Pull request by math-GH**
Closes #4698

hopefully I fix the issue on the root.
Unfortunately I had to use line-height with `rem` unit.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
*Nord theme* is still jumping for me (Firefox and Chrome on Windows 10, 100%), all the other themes are better again 👍🏻 
@Alwaysin Can you give it a try?

**Comment by Alwaysin** [comment]
> _Nord theme_ is still jumping for me (Firefox on Windows 10, 100%), all the other themes are better again 👍🏻 @Alwaysin Can you give it a try?

I have troubles applying the patch:
```
 # curl -L https://github.com/FreshRSS/FreshRSS/pull/4782.patch -s | git apply
error: patch failed: p/themes/Swage/swage.css:149
error: p/themes/Swage/swage.css: patch does not apply
error: patch failed: p/themes/Swage/swage.rtl.css:149
error: p/themes/Swage/swage.rtl.css: patch does not apply

```

**Comment by Alwaysin** [comment]
I got it working by going back to a previous commit. I didn't browse through all the themes but it looks good to me! (origine-compact, flat, pafat, and even nord)

**Comment by aledeg** [comment]
Thank you @Alwaysin for your tests! That's appreciated.

**Comment by Alkarex** [comment]
> I have troubles applying the patch

@Alwaysin If you have checked out FreshRSS by git, the easiest is to continue using git for trying features and going back


```sh
# Get back to clean edge
git fetch --all --prune
git reset --hard upstream/edge
# Apply a patch
git pull https://github.com/math-GH/FreshRSS.git fix-jumping-lines
```

(Using the convention that `upstream/edge` is https://github.com/FreshRSS/FreshRSS.git and `origin/edge` is your own https://github.com/Alwaysin/FreshRSS.git , otherwise adapt the name of the remote accordingly)

Command-line tips can be found at the bottom of GitHub pull requests:

image

**Comment by Alwaysin** [comment]
Thanks for the info @Alkarex. I indeed am on git and it usually works with ```curl -L [...].patch | git apply```. I fint it easier to get the changes this way but it looks like the fix merged earlier on Swage theme is not included here hence the conflict.

I think you need to have specific rights to see wht is on your screenshot, I don't see this. But the instructions otherwise work though!

**Comment by math-GH** [comment]
I fixed hopefully everything.

**Comment by math-GH** [comment]
This PR made an issue with BlueLagoon theme visible. Please merge #4786 before

**Pull request merged**
