### PR TITLE
Improved: unread articles counter

### PR DESCRIPTION
**Pull request by math-GH**
Closes #4068 (Forum discussion)

Changes proposed in this pull request:

- unread count of feeds is now aligned to the right hand side
grafik

How to test the feature manually:

1. see the unread numbers in normal/reading view

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by math-GH** [comment]
@Alkarex Ist there any reason to release this PR with the next bugfix release 1.19.2?

**Comment by Alkarex** [comment]
No, and if not ready, it is not a problem at all

**Comment by math-GH** [comment]
Ready for review. Feedback is welcome.
Please check your favorite themes (colors, contrast)

**Comment by Alkarex** [comment]
Let's release 1.19.2 in the coming days, and wait for 1.20 for this one after all

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
Could you please check the conflicts @math-GH ?

**Comment by math-GH** [comment]
Strange merge conflict. I am not 100% sure whether it is solved correctly or not.

**Comment by Alkarex** [comment]
There was a remaining little problem with the new SASS syntax requiring `variables.$sid-pills`, see https://github.com/FreshRSS/FreshRSS/pull/4173

**Pull request merged**
