### PR TITLE
improved: Nord theme

### PR DESCRIPTION
**Pull request by math-GH**
some improvements of the Nord theme.

### CODE REVIEW

**Comment by math-GH** [comment]
Before:
a border is shown
grafik

After:
no border
grafik

**Comment by math-GH** [comment]
Before:
no hover effect when hovering the "read all" big button
grafik

After:
The tick is blue, when it is not hovered
grafik

While hovering: background color changes and the tick color changes from blue to white
grafik

**Comment by math-GH** [comment]
Nav menu button margin

Before:
grafik

After:
grafik


Before (mobile):
grafik

After (mobile):
grafik

**Comment by Alkarex** [comment]
Looks good 👍🏻

**Comment by math-GH** [comment]
The transition for changing the color while hovering changed, so it feels now a bit faster as before (before it felt slow)

**Comment by math-GH** [comment]
Before: 
grafik

After:
grafik

**Comment by math-GH** [comment]
Before:
grafik

After:
grafik

**Comment by math-GH** [comment]
Attention button

Before:
grafik

After:
grafik


Hovering:
grafik

**Comment by math-GH** [comment]
Dropdown menu was reworked again. See: https://github.com/FreshRSS/FreshRSS/pull/5689#issuecomment-1760172853

Was:

Before:
grafik

After:
Link color, hover color
grafik

**Comment by math-GH** [comment]
ping @joelchrono12: Please have a look here and give feedback if there is something that does not fit to the theme you created

**Comment by math-GH** [comment]
Removed the border of the slider

Before:
grafik

grafik

After:
grafik

grafik

**Comment by math-GH** [comment]
Input borders

Before:
elements are not well aligned
grafik

Scroll bars in the slider
grafik

Focused inputs have a outline
grafik

After:
grey border. elements are aligned
grafik

No scroll bars
grafik

Focused elements have now a blue (it changes from grey) border without a outline
grafik

**Comment by joelchrono12** [comment]
I like all this a lot! Thank you for the improvements. When I originally did this I pretty much just changed the color scheme of the basic theme and a couple of things here and there, but the attention to detail displayed here is great. Thanks again, can't wait to see it updated

**Comment by math-GH** [comment]
Input elements

Before:
No feedback when hovering over an input element

After:
when hovering the input gets an blue border
grafik

**Comment by math-GH** [comment]
Navigation

Before: 
No feedback while hovering.
grafik

After:
feedback while hovering. Active menu item has a highlighted color
grafik

**Comment by math-GH** [comment]
Buttons have now a border

Before:
no border. No hover effekt
grafik

Buttons are sometime not recognizable as button
grafik

After:
Border+ hover effect
grafik

all buttons are visible
grafik

**Comment by math-GH** [comment]
Subscr. Mgm: Borders

Before
grafik

After
grafik

**Comment by math-GH** [comment]
Menu: More empty space to breath

Before:
grafik

After:
grafik

**Comment by math-GH** [comment]
Dropdown menu:

Before:
grafik

grafik

After:
grafik

grafik

**Comment by math-GH** [comment]
sticky buttons

Before:
grafik

grafik

After:
grafik

grafik

**Comment by math-GH** [comment]
Article + Reader view:

Before:
grafik


After:
grafik

**Comment by math-GH** [comment]
user queries

before:
grafik


after:
grafik

**Comment by math-GH** [comment]
Alert info boxes:

Before:
grafik

grafik

grafik

After:
grafik

grafik

grafik

**Comment by math-GH** [comment]
Feed navigation

Before:
grafik


After:
grafik

**Comment by math-GH** [comment]
Log pagination

Before:
grafik

After:
grafik

**Comment by math-GH** [comment]
Ready for review :)

I hope everyone will like it.

Ping @joelchrono12

**Review by Frenzie — APPROVED** [review]
lgtm anyway ;-)

**Comment by joelchrono12** [comment]
> Ready for review :)
> 
> I hope everyone will like it.
> 
> Ping @joelchrono12


I already want to try it out, just push the update already!!!

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
> I already want to try it out, just push the update already!!!

Merged, but it is always good to try before the merge (the easiest method is with git, but Docker is also possible, as well as ZIP and Code Spaces). Note for later, we should collect that somewhere in our documentation, to be able to point to it. Example for docker-compose: https://github.com/FreshRSS/FreshRSS/issues/5668#issuecomment-1732421522

**Comment by Frenzie** [comment]
With plain git you can:

```
# assuming you named the remote upstream, otherwise it's just origin
git fetch upstream pull/1234/head
git checkout FETCH_HEAD
```

**Comment by daffydock** [comment]
Trying the new theme, seems great. Noticed however that the word "Mark As Read" looks grayed out. So it is not as visible. Whether one hovers on it or not, albeit the blue border does light up if one hovers. In general it does look more cohesive and reactive. I like it.

**Comment by math-GH** [comment]
> Noticed however that the word "Mark As Read" looks grayed out. So it is not as visible. Whether one hovers on it or not, albeit the blue border does light up if one hovers. 

Could you please support here with a screenshot?

**Comment by math-GH** [comment]
> > Noticed however that the word "Mark As Read" looks grayed out. So it is not as visible. Whether one hovers on it or not, albeit the blue border does light up if one hovers.
> 
> Could you please support here with a screenshot?

For the documentation: see answer: https://github.com/FreshRSS/FreshRSS/pull/5719#issuecomment-1776709018

**Pull request merged**
