### PR TITLE
Rename template.css

### PR DESCRIPTION
**Pull request by math-GH**
as discussed in https://github.com/FreshRSS/FreshRSS/pull/4641#issuecomment-1257283965

Rename `template.css` to `frss.css`.

I use a separate PR, so that hopefully the file history is kept. And hopefully git/github understands this change for the other PRs.

What I did:
```
> git mv .\template.css .\frss.css
> git log --follow .\frss.css
> git mv .\template.rtl.css .\frss.rtl.css
> git log --follow .\frss.rtl.css
```

### CODE REVIEW

**Review by Alkarex — APPROVED** [review]

**Comment by math-GH** [comment]
Let's merge #4641 before I will resolve this conflict

**Comment by Alkarex** [comment]
Approved after the conflict resolution

**Comment by Alkarex** [comment]
@math-GH I have fixed the conflicts and updated a few missing locations. Could you please double-check?

**Comment by math-GH** [comment]
Looks fine. Let's merge.

**Pull request merged**
