### PR TITLE
Feed attributes only for admin

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/FreshRSS/FreshRSS/pull/1838

### CODE REVIEW

**Comment by Alkarex** [comment]
cURL feed options can be problematic, due to partial feed caching shared between users.
Enabling only for admin users for now.

**Comment by Frenzie** [comment]
What about the SSL?

**Comment by Alkarex** [comment]
@Frenzie timeout and SSL are both some cURL options. Both options risk to affect other users.

**Comment by Frenzie** [comment]
I see. At a glance only timeout made sense to me as something that could be problematic on the server side.

**Comment by Alkarex** [comment]
Yes, for instance with/without SSL could very well retrieve two different version, or retrieve a malicious content (instead of nothing) if someone disables SSL.

**Pull request merged**
