### PR TITLE
docs: fix nginx configuration

### LINKED ISSUE #5193: docs: fix nginx configuration
**Describe the bug**

I tried `Hosted in a subdirectory` type.
https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#hosted-in-a-subdirectory

With using sample nginx configuration, apache will recieve request with `/freshrss/`

```
$ docker compose logs freshrss -f
freshrss  | [Sun Mar 12 13:30:50.843823 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) configured -- resuming normal operations
freshrss  | [Sun Mar 12 13:30:50.843892 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
freshrss  | 122.26.52.129 - - [12/Mar/2023:13:30:52 +0900] "GET /freshrss/ HTTP/1.0" 404 196 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
freshrss  | 122.26.52.129 - - [12/Mar/2023:13:30:52 +0900] "GET /freshrss/ HTTP/1.0" 404 196 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
```

**To Reproduce**
1.  apply https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#hosted-in-a-subdirectory

**Expected behavior**

apache will recieve request with `/`

**Additional context**

Aftre updating format, It seems go well

As-Is
`proxy_pass http://freshrss;`
To-Be
`proxy_pass http://freshrss/;`

### PR DESCRIPTION
**Pull request by witchcraze**
Update nginx configuration in `Hosted in a subdirectory type.`

Closes #5193

Changes proposed in this pull request:

- Change proxy_pass 

As-Is
`proxy_pass http://freshrss;`
To-Be
`proxy_pass http://freshrss/;`

### CODE REVIEW

**Comment by Alkarex** [comment]
Ah, I see that this line was already modified before. Could you please check https://github.com/FreshRSS/FreshRSS/pull/2574 ?

Error-prone nginx configurations are one of the reasons I am recommending Traefik as a reverse proxy, which is designed for such things.

**Comment by Alkarex** [comment]
Related https://github.com/FreshRSS/FreshRSS/pull/3438

**Comment by witchcraze** [comment]
Thank you for your confirmation.

I google-ed "proxy_pass trailing slash", and this page explaines about this.
https://blog.cosnomi.com/posts/674/

From this page ...

```
# Case 1
location /japan/ {
  proxy_pass http://example.jp/
}

# Case 2
location /japan/ {
  proxy_pass http://example.jp
}
```

Case1
http://example.com/japan/hoge -> http://example.jp/hoge
http://example.com/japan/ -> http://example.jp/

Case2
http://example.com/japan/hoge -> http://example.jp/japan/hoge
http://example.com/japan/ -> http://example.jp/japan/

---

In official site, related topic was written

> If proxy_pass is specified without a URI, the request URI is passed to the server in the same form as sent by a client when the > original request is processed, or the full normalized request URI is passed when processing the changed URI:
> ```
> location /some/path/ {
>     proxy_pass http://127.0.0.1;
> }
> ```
> 
> From : [Module ngx\_http\_proxy\_module](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass)

And `Before version 1.1.12, if proxy_pass is specified without a URI, the original request URI might be passed instead of the changed URI in some cases.` is written

----

I checked #2573
This case maybe `Hosted as domain root` type, since `location /` is written in configuration.

----

I checked #3438
All samples show `proxy_pass http://freshrss/`, and it seemes not issue about `proxy_pass`

----

But anyway, I'm not nginx expert. I'll close this if you are ok, since I can not judge this is prpper or not.
In my case/environment, `trailing slash` was required. Just only it.

> Error-prone nginx configurations are one of the reasons I am recommending Traefik as a reverse proxy, which is designed for such things.

Special agree.
In these days, I moved my sites with nginx proxy, but many issues happened...
If more issues happen, I'll try Traefik.


At last, I'm over 5 year user. I love  FreshRSS.

**Comment by Alkarex** [comment]
Thanks for the additional info. That looks correct.

**Pull request merged**
