### PR TITLE
Fixed: clickable link block

### LINKED ISSUE #3120: Impossible to open a link in a new tab on the "clickable link block" if the item is not selected
Context :

I sometimes want to open a link in a new tab (right click > open in a new tab) or to copy the article URL without opening the article on FreshRSS.

Actual :

- The link is not in the "full clickable" zone before opening the article.
- The link is on the "full clickable" zone after opening the article (article title is bold).

This is not comfortable if the title of the article is short.

Expected :

- The link is always in the full clickable zone (without the need to open the article in FresshRSS).

A screenshot with the zone where the link is clickable (right click > open in a new tab) on Firefox Nightly :

### PR DESCRIPTION
**Pull request by math-GH**
Closes #3120

Changes proposed in this pull request:

- improved HTML
- improved CSS

How to test the feature manually:

1. normal view: hover over the title
2. the whole title column is now a "real" link (see the link preview of the browser in the bottom corner)

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alwaysin** [comment]
I don't understand this change. How does one open an article in FreshRSS now?
Each time I click on an article to view it in FreshRSS, it opens the original link in a new tab.

**Comment by ampfinger** [comment]
I'm also not comfortable with this change. Before I'm scrolling through my feeds, open the article in Freshrss if the title is interesting and open in new tab if I want to read further.
Now if I'm clicking the title it's opening directly the new tab.

Is there a chance to make it behave like before or is currently not intentional?

Only option for me is to click on the preview image, then it opens the summary of the current feed.

**Comment by math-GH** [comment]
oh. I see. Will check what is happened here.

**Comment by math-GH** [comment]
I apologize for this bug.
It is fixed with #6452

**Comment by Alwaysin** [comment]
> I apologize for this bug.

No worries, you fixed it very quickly and being on edge is accepting the consequences, and also finding this kind of bugs before it lands on a release.

**Comment by ampfinger** [comment]
> I apologize for this bug. It is fixed with #6452

Dont need to apologize. Thats beta testing and not all use cases can be covered.
Thanks for your work on this project!

**Pull request merged**
