### PR TITLE
Improvement: Configuration; Reading Section: Options reordered

### LINKED ISSUE #596: [feature request] reorganize reading configuration page
After reading #551, it appears to me that it is maybe the right time to reorganize the reading configuration page.

In my mind, "Mark article as read…" should be a list as well as the default filter for articles ("show all articles", "show only unread" and soon a new option).

Maybe we should add also sections like in other configuration pages.

### PR DESCRIPTION
**Pull request by math-GH**
Closes #596

Before:
grafik

After:
see below

Changes proposed in this pull request:

- reordering the settings
- give some headlines of the new groups

How to test the feature manually:

1. go to settings: Reading

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by math-GH** [comment]
First draft for your feedback

grafik

**Comment by math-GH** [comment]
Todo:
i18n for the headlines

**Comment by math-GH** [comment]
No feedback is a good feedback? ;)

**Comment by Alkarex** [comment]
A reorganisation of the various options is needed and welcome, and what you have done so far looks already good 👍🏻

**Comment by math-GH** [comment]
Now it looks like:
grafik

**Pull request merged**
