### PR TITLE
simplified chinese translation

### PR DESCRIPTION
**Pull request by hoilc**
The PR adds simplified chinese translation for FreshRSS.

It's translated from English and some words could be inaccurate.

I will improve it later.

### CODE REVIEW

**Comment by Alkarex** [comment]
Hello @hoilc 
Many thanks for this first translation.
Do you need to change the theme font to include Chinese characters?

**Comment by hoilc** [comment]
Hi @Alkarex

Thanks for reminding me.

I added the default simplified chinese font of Windows and MacOS into templete font-family.

**Comment by Alkarex** [comment]
For the font, I was also thinking of adding glyphs to our OpenSans font (see e.g. https://github.com/FreshRSS/FreshRSS/pull/1032 ). I need to look at it also (I would like to avoid linking to yet another CSS, and also ensure that the font does not become too large - maybe with an option)

**Comment by Alkarex** [comment]
Please add yourself to https://github.com/FreshRSS/FreshRSS/blob/dev/CREDITS.md

**Comment by Alkarex** [comment]
Merged in /dev. Thanks again!

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/5930

**Pull request merged**
