### PR TITLE
Docs: delete 04_Changing_source_code.md

### LINKED ISSUE #5390: Documentation: Page "Changing the source code" is empty
> I saw this: https://freshrss.github.io/FreshRSS/en/developers/03_Backend/04_Changing_source_code.html and this and it was very disappointing...

_Originally posted by @hydrian in https://github.com/FreshRSS/FreshRSS/issues/1053#issuecomment-1542509958_

### PR DESCRIPTION
**Pull request by math-GH**
Closes #5390

Changes proposed in this pull request:

- delete contentless docs pages `04_Changing_source_code.md`

### CODE REVIEW

**Comment by math-GH** [comment]
Please check how to update this files that have references to this files:
- docs\po4a.conf
- docs\i18n\freshrss.fr.po
- docs\i18n\templates\freshrss.pot

**Review by Frenzie — APPROVED** [review]

**Comment by Alkarex** [comment]
I always forget what to do with .po & .pot files. I hope @Frenzie might have the patience to give some hints yet again 🫣

**Comment by Frenzie** [comment]
I think it's gone out of sync unfortunately, but all you theoretically need is make pot. See #3006.

I guess I should've just put in the effort of building po4a all those years ago. Luckily a version properly supporting Markdown is simply in the repos now, but I'm not entirely sure what we'd want GHA to do.

**Comment by Alkarex** [comment]
`make pot` done https://github.com/FreshRSS/FreshRSS/pull/5391/commits/aea7e0517948a5fafab28a53008c36439083c3ab
But it also generates plenty of Mardown files for French, but I have not committed them.

**Pull request merged**
