### PR TITLE
i18n: Add Hebrew translation

### PR DESCRIPTION
**Pull request by mat-mo**
As requested in #673

### CODE REVIEW

**Comment by aledeg** [comment]
@mat-mo I just updated the branch with the hebrew translation with what you did in this PR. There is missing translations.
Could you have a look at that, correct my copy-paste if necessary. Thanks.

**Comment by mat-mo** [comment]
Sorry, i missed what marienfressinaud had done in Dec. I'll look at what you did and try to adjust. Thanks for all your work, both!

**Comment by aledeg** [comment]
Thank you for your contribution. I'll close that PR since it cannot be merge in the current dev branch. Please make a new PR on the hebrew-i18n branch.

**Comment by aledeg** [comment]
Any update on the translation?

**Comment by mat-mo** [comment]
Sorry i didn't get to it last week, I'll try to finish tomorrow.

**Comment by aledeg** [comment]
No rush, I just wanted to know if everything was working properly with the new branch

**Comment by Alkarex** [comment]
Merged in https://github.com/FreshRSS/FreshRSS/commit/f7560c585f211be41b093906e3a8fb5a6071c660

**Pull request closed without merging**
