### PR TITLE
Improve issue template

### PR DESCRIPTION
**Pull request by math-GH**
Using the issue template form:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

New form:
grafik

It will replace the old very text based form:
grafik

Benefit: better UX while writing the bug issue template

How to test the form before committing this PR: see this repository: https://github.com/math-GH/issue_forms/issues

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
Better could be debatable (e.g., having to set `-` or something instead of removing irrelevant sections) but sure, why not.

**Comment by Frenzie** [comment]
Actually, what happens with this if you leave something that isn't required empty? Does the system filter it out so it doesn't pollute the issue report?

**Comment by math-GH** [comment]
> Actually, what happens with this if you leave something that isn't required empty? Does the system filter it out so it doesn't pollute the issue report?

Try it out here ;) https://github.com/math-GH/issue_forms/issues

grafik

**Comment by Alkarex** [comment]
Installation type could include git. Web server type would also be good

**Comment by Frenzie** [comment]
I find the "no response" a tad disappointing really, but oh well, it's not too bad.

**Comment by math-GH** [comment]
Less "no response" fields. Added more env information. Made the FreshRSS version mandatory.

grafik

**Pull request merged**
