### PR TITLE
Allow multiple authors on enclosures

### LINKED ISSUE #5066: [BUG] RSS standard: multiple credits not shown
**Describe the bug**
Only the first credit of enclosures is shown of the 5th example of https://www.rssboard.org/media-rss#examples (as RSS feed: https://raw.githubusercontent.com/math-GH/testfeed/main/rssboard.org/example5.xml)

grafik

That is the source:
grafik

**To Reproduce**
1. subscribe to https://raw.githubusercontent.com/math-GH/testfeed/main/rssboard.org/example5.xml
2. see that only the first credit is shown

**Expected behavior**
Both credits are shown

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.0-dev

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/5066

### CODE REVIEW

**Comment by math-GH** [comment]
Does not work with this feed:
https://raw.githubusercontent.com/math-GH/testfeed/main/rssboard.org/example5.xml#force_feed

grafik

**Comment by Alkarex** [comment]
This is how it looks for me:

image

**Comment by math-GH** [comment]
OK. I removed and added again the feed. Now it works.

**Review by math-GH — APPROVED** [review]
looks good for me

**Pull request merged**
