### PR TITLE
Improve: reduce size when tagEntry

### PR DESCRIPTION
**Pull request by BlueWhale235**
Changes proposed in this pull request:

-When I add a tag to a article, I find that the response is too large. I think it needn't request all contents. So I add a "ajax" opinion.
-Screen Shots:
-Before
屏幕截图 2022-05-15 141444

-After
屏幕截图 2022-05-15 135254

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [x] documentation updated

### CODE REVIEW

**Review by Frenzie — APPROVED** [review]
If that all works, lgtm. Btw, not directly related to this PR but the indentation looks a bit weird on those last 4 lines.

**Comment by BlueWhale235** [comment]
I just add a line, this is what the previous person left behind.  
Also, what does **"lgtm"** mean? I don't really understand because I'm not a native English speaker.

**Comment by Alkarex** [comment]
@BuleWhale Thanks, good idea with this PR. *lgtm* means *looks good to me*

**Comment by Alkarex** [comment]
@Frenzie No indentation problem, just a strange GitHub visualisation with a difference between the lines that are part of the patch or not

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/pull/4310

**Comment by Frenzie** [comment]
@Alkarex You mean this is a visualization problem with regard to the number of equivalent spaces it chooses for tabs?
Screenshot 2022-05-15 at 13-54-07 Improve reduce size when tagEntry by BuleWhale · Pull Request #4366 · FreshRSS_FreshRSS

**Comment by Alkarex** [comment]
Indeed @Frenzie . It looks fine when looking at the full document

**Pull request merged**
