### PR TITLE
Added bottom nav padding for iOS #4740

### LINKED ISSUE #4740: [BUG] Feed navigation overlaps safe area in iOS
**Describe the bug**
When FreshRSS is used as an app within iOS (using 'Add to Homescreen' from Safari), the bottom navigation bar overlaps with the swipe up for changing applications. Because of this the navigation buttons can be hard to use unless you use a theme with large buttons.

**To Reproduce**
1. In Safari, use 'Add to Home Screen' from the 'Share' menu
2. Open FreshRSS using the new item on the home screen
3. Try to use the navigation buttons at the bottom. They only work if you manage to press them above the safe area

**Expected behavior**
The bottom navigation should have sufficient padding on iOS to push it above the safe area

**Screenshots**
WIN_20221018_13_32_22_Pro

**Environment information (please complete the following information):**
- Device: iPhone 12
- OS: iOS 16.0.2
- Browser: N/A
- FreshRSS version: 1.20.0
- Installation type: Docker

**Additional context**
This should be able to be fixed using ```padding-bottom: env(safe-area-inset-bottom);```

That should add enough padding for iOS without affecting other devices.

### PR DESCRIPTION
**Pull request by acbgbca**
Closes #4740 

Changes proposed in this pull request:
- Added additional bottom padding to the navigation when required. This means the navigation no longer overlaps the safe area in iOS. The viewport meta tag changes were required for safe-area-inset-bottom to have a value.

How to test the feature manually:
1. Add FreshRSS to the iOS Home screen
2. Open the application
3. Note that the menu no longer overlaps the safe area

I have observed the following based on my testing:
* Desktop browser - no change
* Safari in iOS, portrait - no change (iOS has the URL bar at the bottom which covers the safe area)
* Safari in iOS, landscape - The bottom navigation has the padding added pushing it above the safe area
* iOS as home screen app - The navigation has the padding addedd
* Android - Unfortunately I have no android device on which to test. However unless the device specifically sets 'safe-area-inset-bottom' it should have no change

WIN_20221018_13_48_43_Pro

Pull request checklist:

- [X] clear commit messages
- [X] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by math-GH** [comment]
Should be fine. Cannot test it because I do not have a iPhone device.

**Comment by Alkarex** [comment]
> Should be fine. Cannot test it because I do not have a iPhone device.

The main thing is to make sure there is no regression on other platforms

**Comment by math-GH** [comment]
> > Should be fine. Cannot test it because I do not have a iPhone device.
> 
> The main thing is to make sure there is no regression on other platforms

I checked it in a very quick try out on my mobile phone (Android, with a standard rectangle screen). It is fine. But I cannot check if it really works ;)

**Comment by Alkarex** [comment]
Ref https://developer.mozilla.org/docs/Web/CSS/env

**Pull request merged**
