### PR TITLE
More improvements/fixes of Nord theme

### PR DESCRIPTION
**Pull request by math-GH**
Ref #5689
Ref #5719

Some more improvements of `Nord` theme

### CODE REVIEW

**Comment by math-GH** [comment]
Before:

1) in mobile view: the favicons had a grey background on the right hand side
2) the unread counter was not perfect positioned
grafik

After:
grafik

**Comment by math-GH** [comment]
Before:
the color of the table border where missed, so it was just plain white.
grafik


After:
it has a dark color
grafik

**Comment by Alkarex** [comment]
How much till its ready, more or less? I think we are ready for the release of 1.22.1

**Comment by math-GH** [comment]
let's merge it here :)

**Pull request merged**
