### PR TITLE
Docker: Use Apache remoteip

### LINKED ISSUE #3224: Log of unsuccessful login attempts with external IP
Hi.

I was trying to configure fail2ban with FreshRSS running in a Docker container and I have several issues.

First one: is there any global log that can be accessed from outside the container to be processed by a fail2ban instance? As far as I can see, there is only a per user log in the data foder, but there I can not find the 403 lines that are being registered with the offending IP.

Second one: Regarding the IP, in mi instance, what I see is the local IP, not the external one, which is the one that must be blocked if several attempts to login fail. Would it be possible to log the external IP from which the container is being accessed? I am running the container with an isolated bridge network as recommended in the docs.

Thanks in advance for your help.

### PR DESCRIPTION
**Pull request by Alkarex**
#fix https://github.com/FreshRSS/FreshRSS/issues/3224
Log the client remote IP instead of the local proxy IP
https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html

### CODE REVIEW

**Comment by Alkarex** [comment]
@tonitonae Would you be able to test this PR?
The Docker image needs to be built manually until it lands in our main branch:

```sh
git clone https://github.com/FreshRSS/FreshRSS.git
cd FreshRSS
git pull https://github.com/Alkarex/FreshRSS.git remoteip
docker build --pull --tag freshrss/freshrss:dev -f Docker/Dockerfile .
```

**Comment by tonitonae** [comment]
Not working for me. Still showing the internal IP:

> FreshRSS[29]: [xxxxx] [Wed, 14 Oct 2020 23:15:24 +0200] [warning] --- Password mismatch for user=test, nonce=, c=$2a$04$FFVv.g2Hxrjw62lGbnsq2eaSO6erQvQJuA7ubjzuvSBInwf1qPvcu
> 172.18.0.1 - - [14/Oct/2020:23:15:24 +0200] "POST /i/?c=auth&a=login HTTP/1.1" 403 5952 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"

Sorry...

**Comment by Alkarex** [comment]
Sorry, checking out the proper branch was lacking in my instructions:

```sh
git pull https://github.com/Alkarex/FreshRSS.git remoteip
```

**Comment by tonitonae** [comment]
Yes, did not realize neither.

Tested and working here. Thanks!

**Comment by Alkarex** [comment]
Reworked in https://github.com/FreshRSS/FreshRSS/pull/5549
Tests welcome

**Pull request merged**
