### PR TITLE
Fix CSS selector encoding

### LINKED ISSUE #6229: [BUG] Article selector is HTML escaped
**Describe the bug**
The article CSS selector is being passed to CSSXPath with some characters encoded as XML entities. The selector `[id="main"]` becomes `[id=&quot;main&quot;]` which is converted to `.//*[@id="&quot;main&quot;")]`

**To Reproduce**
1. Input an Article CSS Selector with double quotes
2. Submit due to #6228
3. Click the preview button by the selector
4. CSSXpath has now been passed a mangled selector (I debugged by adding an `error_log` statement to Translator.php)

**Expected behavior**
The selector should be unescaped by the time it reaches CSSXpath.

**Environment information (please complete the following information):**
- Device: ThinkPad A485
- OS: Void Linux
- Browser: Firefox 124.0
- FreshRSS version: 1.23.2-dev 1c0b8a7
- Database version: PostgreSQL 16.2
- PHP version: 8.2.7
- Installation type: Docker self hosted

### LINKED ISSUE #6266: [Bug] Preview of CSS selector uses the one saved and not the one entered
### Describe the bug

I find it misleading that when previewing a CSS selector, it uses the one that is saved and not the one entered. When one doesn't really know what to input there and goes by trial and error, it is very cumbersome to each time save the settings and go back to the config to be able to preview the selector.

Plus, I'm not sure if "CSS selector of the elements to remove" is taken into account in the previewing, and if it is the case it probably also needs to be saved.

### To Reproduce

1. Go to a feed settings
2. Change the value of "Article CSS selector on original website"
4. Click the preview button
6. See the old value used

### Expected behavior

Using the newly entered value

### FreshRSS version

latest edge

### Environment information

- Database version: MariaDB 10.11
- PHP version: PHP 8.2
- Installation type: git
- -Web server type: Apache
- Device: Laptop
- OS: Win11
- Browser: Chrome 124

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Alkarex**
fix https://github.com/FreshRSS/FreshRSS/issues/6229
fix https://github.com/FreshRSS/FreshRSS/issues/6266#issuecomment-2090432818

### CODE REVIEW

**Comment by math-GH** [comment]
A point of view from UI/UX: If the "eye" button uses both inputs then both inputs should have its own `<fieldset>` with its own buttons. One button could be the "eye" button then. (others: save, cancel)
grafik

**Comment by mrnoname1000** [comment]
From some quick testing this seems to fix both bugs!

**Comment by math-GH** [comment]
While testing I found this bug:

if the last element of this list is empty (last character is a comma):
grafik

grafik

**Comment by Alkarex** [comment]
Indeed @math-GH , this UX could be improved. There are also all the other parameters below, which are not used by the preview. But let's merge the fixed bugs already.

> if the last element of this list is empty (last character is a comma)

Let me try to make another PR for that

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6428

**Pull request merged**
