### PR TITLE
Add a Docker-native solution for updating feeds

### PR DESCRIPTION
**Pull request by joestump**
Changes proposed in this pull request:

Adds a section to the administration documentation on how to set up automatic feed updates in a Docker-native way.

How to test the feature manually:

1. Follow the docs only use `10s` instead of `30m`.
2. Watch the logs of your `ofelia` container
3. Watch it refresh your feeds.

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [x] unit tests written (optional if too hard)
- [x] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

### CODE REVIEW

**Comment by Alkarex** [comment]
Hello,
Can you please explain some more what you are trying to achieve there, in particular the usecase?

**Comment by joestump** [comment]
@Alkarex  I use exclusively Docker for running myself-hosted apps. Docker has no cron facility. Having maintenance operations reside _outside_ of the container/pod/compose project is considered somewhat of an antipattern in the Docker/K8s communities. (e.g. Using `cron` on the host to control/manage processes in the container.) Ofelia offers a Docker-native approach for cron-like tasks in Docker.

This documents how to do [automatic feed refreshes](http://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html) on a regular cadence using Ofelia, which obviates the need to have a cron job running on another host for people using Docker/Docker Compose.

If you'd prefer, I can move this example to the Docker Compose docs.

**Comment by Alkarex** [comment]
We already have a built-in cron solution, for instance by passing an environment variable such as `-e 'CRON_MIN=1,31'`

https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#cron-job-to-automatically-refresh-feeds

**Comment by joestump** [comment]
@Alkarex ah my bad, not sure how I missed it in those docs. The doc I updated here is top results for various "automated FreshRSS" searches; should we make a pointer to the Docker docs? I'll close this PR and issue another doc update if you'd like.

**Comment by Alkarex** [comment]
> should we make a pointer to the Docker docs?

Good idea. Maybe just indicating that when running Docker, there is a built-in cron in our images, with a link 👍🏻

**Pull request closed without merging**
