### PR TITLE
Fix 4712

### LINKED ISSUE #4712: UI regression icons click areas
The click area for the icons such as mark-as-read / favourite have become much smaller, generating many wrong clicks.

This seems to be due to a mislocated padding rule. Regression probably due to https://github.com/FreshRSS/FreshRSS/pull/4671

In FreshRSS 1.20.0:

image

In edge:

image

### PR DESCRIPTION
**Pull request by math-GH**
Closes #4712

Changes proposed in this pull request:

- padding

How to test the feature manually:
see #4712

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

### CODE REVIEW

**Comment by Alkarex** [comment]
Better, but not quite the full area as it was before. There is still some margin/padding at the top and bottom, which would be nice to remove:

image

**Comment by math-GH** [comment]
Is it just the Pafat theme?

**Comment by Alkarex** [comment]
There is also a bit of padding/margin in e.g. Origine, although a bit less than in Pafat

image

**Comment by math-GH** [comment]
Pafat is now fixed.

To make it clear: This is just a fix to make it work again. The root cause of all this issues are much deeper and it needs a refactoring of all themes.

**Comment by Alkarex** [comment]
> To make it clear: This is just a fix to make it work again. The root cause of all this issues are much deeper and it needs a refactoring of all themes.

Thanks, and that is fine for now. I would just like to fix the regressions before releasing 1.20.1

**Pull request merged**
