### PR TITLE
lire app

### PR DESCRIPTION
**Pull request by gingerbeardman**
add lire, sort alphabetically

Pull request checklist:

- [x] clear commit messages
- [x] documentation updated

### CODE REVIEW

**Comment by Alkarex** [comment]
Hello and thanks :-)
The order was more or less by (my) subjective perception of maturity, and more or less sorted by platforms. I would rather like to keep the previous order for now :-)

**Comment by gingerbeardman** [comment]
OK, no worries!

I will let you decide where to put lire app.

**Comment by Alkarex** [comment]
Hi again,
I have updated inside this PR to keep your credits :-)
Can you confirm that this app is using the Fever API to interact with FreshRSS (and not through the Google Reader API)?
To be sure, would you happen to have some logs of the requests made to your server?

**Comment by gingerbeardman** [comment]
Thanks!

I have only used the demo (without FreshRSS option) but read in the docs that it supports FreshRSS. The demo was a bit quirky so I decided not to buy the app. 

But, I have asked the developer (using Twitter) and will report back.

**Comment by gingerbeardman** [comment]
"It uses the Google Reader API."

https://twitter.com/LireApp/status/1561756986701516800

**Comment by Alkarex** [comment]
Thanks, updated accordingly

**Pull request merged**
